emit:
  - "@azure-tools/typespec-autorest"
  - "@typespec/openapi3"
  - "@azure-tools/typespec-python"
  - "@azure-tools/typespec-ts"
  - "@typespec/http-client-js"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    output-file: "{emitter-output-dir}/{service-name}/{version}/openapi.json"
  "@azure-tools/typespec-python":
    namespace: "contoso.benchmarkfull"
    package-mode: dataplane
  "@azure-tools/typespec-ts":
    flavor: azure
    package-details:
      name: "@azure-rest/contoso-benchmarkfull"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
