import type { ServerTypeRef } from "../model.js";

/** Renders a {@link ServerTypeRef} as a TypeScript type expression. */
export function renderTypeRef(type: ServerTypeRef): string {
  switch (type.kind) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "unknown":
      return "unknown";
    case "model":
      return type.name;
    case "array":
      return `${wrapIfUnion(renderTypeRef(type.element))}[]`;
    case "literal":
      return typeof type.value === "string" ? JSON.stringify(type.value) : String(type.value);
  }
}

function wrapIfUnion(rendered: string): string {
  return rendered.includes(" ") ? `(${rendered})` : rendered;
}

const GENERATED_FILE_HEADER = `// This file was automatically generated by @azure-tools/typespec-azurite-emitter-pilot.
// Do not edit this file manually; re-run \`tsp compile\` to regenerate it.
`;

export function renderFileHeader(): string {
  return GENERATED_FILE_HEADER;
}
