import type { ServerTypeRef } from "../model.js";

/** Renders a {@link ServerTypeRef} as a TypeScript type expression. */
export function renderTypeRef(type: ServerTypeRef): string {
  switch (type.kind) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "unknown":
      return "unknown";
    case "model":
      return type.name;
    case "array":
      return `${wrapIfUnion(renderTypeRef(type.element))}[]`;
    case "literal":
      return typeof type.value === "string" ? JSON.stringify(type.value) : String(type.value);
  }
}

function wrapIfUnion(rendered: string): string {
  return rendered.includes(" ") ? `(${rendered})` : rendered;
}

/**
 * Collects the names of every `model`-kind type reachable from `type` (including through
 * `array` element types), so callers can emit a single `import type { ... } from "./models.js";`
 * line. Found via a real end-to-end check against Azurite's own `tsc` build: without this, a
 * generated `operations.ts` that uses a model type (e.g. a request/response body) in a position
 * other than `models.ts` itself fails to compile with `TS2304: Cannot find name`.
 */
export function collectModelRefs(type: ServerTypeRef, into: Set<string>): void {
  switch (type.kind) {
    case "model":
      into.add(type.name);
      return;
    case "array":
      collectModelRefs(type.element, into);
      return;
    default:
      return;
  }
}

const GENERATED_FILE_HEADER = `// This file was automatically generated by @azure-tools/typespec-azurite-emitter-pilot.
// Do not edit this file manually; re-run \`tsp compile\` to regenerate it.
`;

export function renderFileHeader(): string {
  return GENERATED_FILE_HEADER;
}
