# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    labels: [] # conflict with our labels in labels.ts

  # Auto update the cadl-ranch-specs version used for e2e tests. It is pinned instead of always using the latest so we don't have a failure showing in random PRs blocking the flow.
  - package-ecosystem: "npm"
    directory: "/packages/e2e-tests/cadl-ranch-specs"
    schedule:
      interval: "daily"
    labels: [] # conflict with our labels in labels.ts
