baseBranch: main
versionPolicies:
  - name: typespec-azure
    type: lockstep
    step: minor
    packages:
      - "@azure-tools/typespec-autorest"
      - "@azure-tools/typespec-azure-core"
      - "@azure-tools/typespec-azure-resource-manager"
      - "@azure-tools/typespec-client-generator-core"
ignore:
  - "@typespec/*"
