packages:
  - packages/*
  - core/ # Install core workspace dependencies too. Needed for prettier plugins
  - website/
  - eng/feeds/
  - core/packages/*
  - "!core/packages/http-client-csharp/**"
  - "!core/packages/http-client-java/**"
  - "!core/packages/http-client-python/**"
overrides:
  rollup: 4.49.0 # Regression in 4.50.0 https://github.com/rollup/rollup/issues/6099
