// Generated by `pnpm gen:scenario-suites`. Do not edit by hand.
import { resolvePath } from "@typespec/compiler";
import { describeScenarioFile } from "../scenario-runner.js";

describeScenarioFile(
  resolvePath(import.meta.dirname, "../scenarios/fake-text-request-body-scalars.md"),
);
