// Generated by `pnpm gen:scenario-suites`. Do not edit by hand.
import { resolvePath } from "@typespec/compiler";
import { describeScenarioFile } from "../scenario-runner.js";

describeScenarioFile(resolvePath(import.meta.dirname, "../scenarios/non-string-path-params-client-defaults.md"));
