// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package contentnegotiation;

public final class ReadmeSamples {
    public void readmeSamples() {
        // BEGIN: contentnegotiation.readme
        // END: contentnegotiation.readme
    }
}
