// Generated by `npm run gen:scenario-suites`. Do not edit by hand.
import { describe } from "vitest";
import { describeScenarioDir } from "../scenario-runner.js";

describe("Scenarios: empty-project", function () {
  describeScenarioDir("./test/modular-unit/scenarios/empty-project");
});
