// Generated by `pnpm gen:scenario-suites`. Do not edit by hand.
import { describe } from "vitest";
import { describeScenarioDir } from "../scenario-runner.js";

describe("Scenarios: models/response", function () {
  describeScenarioDir("./test/modular-unit/scenarios/models/response");
});
