// Generated by `npm run gen:scenario-suites`. Do not edit by hand.
import { describe } from "vitest";
import { describeScenarioDir } from "../scenario-runner.js";

describe("Scenarios: models/serialization", function () {
  describeScenarioDir("./test/modular-unit/scenarios/models/serialization");
});
