// Generated by `pnpm gen:scenario-suites`. Do not edit by hand.
import { describe } from "vitest";
import { describeScenarioDir } from "../scenario-runner.js";

describe("Scenarios: operations", function () {
  describeScenarioDir("./test/modular-unit/scenarios/operations");
});
