// Generated by `pnpm gen:scenario-suites`. Do not edit by hand.
import { describe } from "vitest";
import { describeScenarioDir } from "../scenario-runner.js";

describe("Scenarios: samples/property-flatten", function () {
  describeScenarioDir("./test/modular-unit/scenarios/samples/property-flatten");
});
