// Generated by `npm run gen:scenario-suites`. Do not edit by hand.
import { describe } from "vitest";
import { describeScenarioDir } from "../scenario-runner.js";

describe("Scenarios: samples/client/enable-hierarchy", function () {
  describeScenarioDir("./test/modular-unit/scenarios/samples/client/enable-hierarchy");
});
