// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package contentnegotiation.models;

/**
 * Defines values for GetAvatarContentType.
 */
public enum GetAvatarContentType {
    /**
     * Enum value image/png.
     */
    IMAGE_PNG("image/png"),

    /**
     * Enum value image/jpeg.
     */
    IMAGE_JPEG("image/jpeg");

    /**
     * The actual serialized value for a GetAvatarContentType instance.
     */
    private final String value;

    GetAvatarContentType(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a GetAvatarContentType instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed GetAvatarContentType object, or null if unable to parse.
     */
    public static GetAvatarContentType fromString(String value) {
        if (value == null) {
            return null;
        }
        GetAvatarContentType[] items = GetAvatarContentType.values();
        for (GetAvatarContentType item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
