/**
 * All diff kinds recognized by the tool.
 *
 * A kind being present here does not by itself mean that the comparison engine
 * can produce it. See `diffKindCatalog` for implementation status.
 */
export const diffKinds = [
  "ApiVersionRemoved",
  "ApiVersionAdded",
  "AuthSchemeRemoved",
  "AuthSchemeAdded",
  "OAuthScopeAdded",
  "OAuthScopeRemoved",
  "OperationRemoved",
  "OperationAdded",
  "OperationRouteChanged",
  "RequestPathParameterAdded",
  "RequestPathParameterRemoved",
  "RequestQueryParameterAdded",
  "RequestQueryParameterRemoved",
  "RequestHeaderAdded",
  "RequestHeaderRemoved",
  "RequestParameterRenamed",
  "RequestParameterMadeRequired",
  "RequestParameterMadeOptional",
  "RequestParameterDefaultChanged",
  "RequestParameterLocationChanged",
  "RequestPropertyAdded",
  "RequestPropertyRemoved",
  "RequestPropertyRenamed",
  "RequestPropertyTypeChanged",
  "RequestPropertyTypeNarrowed",
  "RequestPropertyTypeWidened",
  "RequestPropertyMadeRequired",
  "RequestPropertyMadeOptional",
  "RequestPropertyDefaultChanged",
  "RequestTypeChanged",
  "RequestTypeNarrowed",
  "RequestTypeWidened",
  "RequestTypeKindChanged",
  "RequestEncodingChanged",
  "RequestConstraintStrengthened",
  "RequestConstraintRelaxed",
  "RequestContentTypeAdded",
  "RequestContentTypeRemoved",
  "ResponsePropertyAdded",
  "ResponsePropertyRemoved",
  "ResponsePropertyRenamed",
  "ResponsePropertyTypeChanged",
  "ResponsePropertyTypeNarrowed",
  "ResponsePropertyTypeWidened",
  "ResponsePropertyMadeRequired",
  "ResponsePropertyMadeOptional",
  "ResponseTypeChanged",
  "ResponseTypeNarrowed",
  "ResponseTypeWidened",
  "ResponseTypeKindChanged",
  "ResponseEncodingChanged",
  "ResponseConstraintStrengthened",
  "ResponseConstraintRelaxed",
  "ResponseStatusCodeAdded",
  "ResponseStatusCodeRemoved",
  "ResponseContentTypeAdded",
  "ResponseContentTypeRemoved",
  "ResponseHeaderAdded",
  "ResponseHeaderRemoved",
  "ErrorResponseAdded",
  "ErrorResponseRemoved",
  "TypeKindChanged",
  "EnumerationMemberAdded",
  "EnumerationMemberRemoved",
  "EnumerationOpened",
  "EnumerationClosed",
  "DiscriminatorChanged",
  "DefaultValueAdded",
  "DefaultValueRemoved",
  "DefaultValueChanged",
  "ResourcePropertyAdded",
  "ResourcePropertyRemoved",
  "ResourcePropertyRenamed",
  "ResourcePropertyTypeChanged",
  "ResourcePropertyTypeNarrowed",
  "ResourcePropertyTypeWidened",
  "ResourcePropertyMadeRequired",
  "ResourcePropertyMadeOptional",
] as const;

export type DiffKind = (typeof diffKinds)[number];

const diffKindSet: ReadonlySet<string> = new Set(diffKinds);

export function isDiffKind(value: string): value is DiffKind {
  return diffKindSet.has(value);
}
