emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    arm-types-dir: "{project-root}/common-types"
    arm-resource-flattening: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
