emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    arm-types-dir: "{project-root}/common-types"
linter:
  extends:
    # - "@azure-tools/typespec-azure-resource-manager/all"
    - "@azure-tools/typespec-azure-specs-rulesets/resource-manager"
  enable:
    "@azure-tools/typespec-azure-core/no-enum": true
