// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

module contentnegotiation {
    requires transitive com.azure.core;

    exports contentnegotiation;
    exports contentnegotiation.models;

    opens contentnegotiation.models to com.azure.core;
}
