/**
 * Generates one vitest test file per "leaf" scenario directory (a directory
 * that directly contains `.md` scenario files) under
 * `test/modular-unit/scenarios`. Splitting scenarios across many small test
 * files lets vitest run them in parallel worker processes, which dramatically
 * reduces wall-clock time and per-worker memory.
 *
 * Run with: `pnpm gen:scenario-suites`
 *
 * The `coverage` guard test in `scenario-suites.guard.test.ts` fails if the
 * generated files drift from the scenario directory tree, prompting a re-run.
 */
import { existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from "fs";
import path from "path";

const SCENARIOS_ROOT = path.join("test", "modular-unit", "scenarios");
const SUITES_DIR = path.join("test", "modular-unit", "scenario-suites");

function getLeafScenarioDirs(root: string): string[] {
  const result: string[] = [];
  function walk(dir: string): void {
    let hasMd = false;
    for (const child of readdirSync(dir)) {
      const fullPath = path.join(dir, child);
      const stat = statSync(fullPath);
      if (stat.isDirectory()) {
        walk(fullPath);
      } else if (child.endsWith(".md")) {
        hasMd = true;
      }
    }
    if (hasMd) {
      result.push(path.relative(root, dir));
    }
  }
  walk(root);
  return result.sort();
}

/** Encode a leaf directory's relative path into a flat test-file base name. */
export function suiteFileName(relDir: string): string {
  return relDir.split(/[\\/]/).join("__") + ".test.ts";
}

function suiteFileContent(relDir: string): string {
  const posixRel = relDir.split(path.sep).join("/");
  const location = `./test/modular-unit/scenarios/${posixRel}`;
  return `// Generated by \`pnpm gen:scenario-suites\`. Do not edit by hand.
import { describe } from "vitest";
import { describeScenarioDir } from "../scenario-runner.js";

describe("Scenarios: ${posixRel}", function () {
  describeScenarioDir("${location}");
});
`;
}

function main(): void {
  const leafDirs = getLeafScenarioDirs(SCENARIOS_ROOT);

  if (!existsSync(SUITES_DIR)) {
    mkdirSync(SUITES_DIR, { recursive: true });
  }

  // Remove any previously generated suite files so deletions are reflected.
  for (const file of readdirSync(SUITES_DIR)) {
    if (file.endsWith(".test.ts")) {
      rmSync(path.join(SUITES_DIR, file));
    }
  }

  for (const relDir of leafDirs) {
    writeFileSync(path.join(SUITES_DIR, suiteFileName(relDir)), suiteFileContent(relDir));
  }

  // eslint-disable-next-line no-console
  console.log(`Generated ${leafDirs.length} scenario suite files in ${SUITES_DIR}`);
}

main();
