export const GENERATED_FILE_HEADER = `// This file was automatically generated by @azure-tools/typespec-azurite-emitter.
// Do not edit this file manually; re-run \`tsp compile\` to regenerate it.
`;
