const GENERATED_FILE_HEADER = `// This file was automatically generated by @azure-tools/typespec-azurite-emitter.
// Do not edit this file manually; re-run \`tsp compile\` to regenerate it.
`;

export function renderFileHeader(): string {
  return GENERATED_FILE_HEADER;
}

export const GENERATED_FILE_HEADER_COMMENT =
  "This file was automatically generated by @azure-tools/typespec-azurite-emitter.\nDo not edit this file manually; re-run `tsp compile` to regenerate it.";
