// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package contentnegotiation;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;
import com.azure.core.util.FluxUtil;
import contentnegotiation.implementation.SameBodySingleOperationsImpl;
import contentnegotiation.models.GetAvatarContentType;
import reactor.core.publisher.Mono;

/**
 * Initializes a new instance of the asynchronous ContentNegotiationClient type.
 */
@ServiceClient(builder = ContentNegotiationClientBuilder.class, isAsync = true)
public final class ContentNegotiationAsyncClient {
    @Generated
    private final SameBodySingleOperationsImpl serviceClient;

    /**
     * Initializes an instance of ContentNegotiationAsyncClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    ContentNegotiationAsyncClient(SameBodySingleOperationsImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * The getAvatar operation.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * BinaryData
     * }
     * </pre>
     * 
     * @param format The format parameter.
     * @param accept The accept parameter. Allowed values: "image/png", "image/jpeg".
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> getAvatarWithResponse(String format, String accept,
        RequestOptions requestOptions) {
        return this.serviceClient.getAvatarWithResponseAsync(format, accept, requestOptions);
    }

    /**
     * The getAvatar operation.
     * 
     * @param format The format parameter.
     * @param accept The accept parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response body on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<BinaryData> getAvatar(String format, GetAvatarContentType accept) {
        // Generated convenience method for getAvatarWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return getAvatarWithResponse(format, accept.toString(), requestOptions).flatMap(FluxUtil::toMono);
    }
}
