emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}"
    azure-resource-provider-folder: "resource-manager"
    output-file: "{emitter-output-dir}/{version-status}/{version}/widget.json"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
  "@azure-tools/typespec-csharp":
    emitter-output-dir: "{output-dir}/{service-dir}/Azure.ResourceManager.Contoso"
    clear-output-folder: true
    model-namespace: false
    namespace: "Azure.ResourceManager.Contoso"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-contoso"
    namespace: "azure.mgmt.contoso"
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-contoso"
    namespace: "com.azure.resourcemanager.contoso"
    service-name: "contoso"
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-contoso"
    experimental-extensible-enums: true
    flavor: azure
    package-details:
      name: "@azure/arm-contoso"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/contoso"
    emitter-output-dir: "{output-dir}/{service-dir}/armcontoso"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armcontoso"
    fix-const-stuttering: true
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
