import { createHash } from "crypto";
import { mkdirSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";
import { format, resolveConfig } from "prettier";
import process from "process";

const sourceRepository = "Azure/azure-sdk-for-net";
const sourceRef = "main";
const sourceBaseUrl = `https://raw.githubusercontent.com/${sourceRepository}/${sourceRef}/sdk/tools/Azure.SdkAnalyzers/src`;
const reservedNamesPath = "sdk/tools/Azure.SdkAnalyzers/src/reserved-type-names.txt";
const reservedQualifiedNamesPath =
  "sdk/tools/Azure.SdkAnalyzers/src/reserved-type-qualified-names.txt";
const outputPath = resolve(
  import.meta.dirname,
  "..",
  "..",
  "packages",
  "typespec-client-generator-core",
  "src",
  "rules",
  "azc0034-reserved-type-names.generated.ts",
);

interface CatalogEntry {
  readonly name: string;
  readonly conflictName: string;
  readonly packageName: string;
}

async function fetchText(url: string): Promise<string> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }
  return response.text();
}

function normalizeNewlines(text: string): string {
  return text.replace(/\r\n/g, "\n").trimEnd();
}

function hash(text: string): string {
  return createHash("sha256").update(text).digest("hex").toUpperCase();
}

function getQualifiedTypeNameLastSegment(qualifiedName: string): string {
  return qualifiedName.includes(".")
    ? qualifiedName.slice(qualifiedName.lastIndexOf(".") + 1)
    : qualifiedName;
}

function parseCatalog(namesText: string, qualifiedNamesText: string): CatalogEntry[] {
  const names = normalizeNewlines(namesText).split("\n");
  const qualifiedNames = normalizeNewlines(qualifiedNamesText).split("\n");

  if (names.length !== qualifiedNames.length) {
    throw new Error(
      `Catalog files must have the same line count. Got ${names.length} names and ${qualifiedNames.length} qualified names.`,
    );
  }

  const seen = new Set<string>();
  const entries: CatalogEntry[] = [];
  for (let index = 0; index < names.length; index++) {
    const line = index + 1;
    const name = names[index];
    const qualifiedName = qualifiedNames[index];

    if (name.trim() === "") {
      throw new Error(`reserved-type-names.txt has a blank line at ${line}.`);
    }
    if (qualifiedName.trim() === "") {
      throw new Error(`reserved-type-qualified-names.txt has a blank line at ${line}.`);
    }
    if (index > 0 && names[index - 1] > name) {
      throw new Error(
        `reserved-type-names.txt must be sorted. "${names[index - 1]}" appears before "${name}".`,
      );
    }
    if (seen.has(name)) {
      throw new Error(`reserved-type-names.txt has duplicate name "${name}" at line ${line}.`);
    }
    seen.add(name);

    const [conflictName, packageName] = qualifiedName.split(";", 2);
    if (!conflictName || !packageName) {
      throw new Error(
        `reserved-type-qualified-names.txt line ${line} must use "conflictName;packageName".`,
      );
    }

    const lastSegment = getQualifiedTypeNameLastSegment(conflictName);
    if (lastSegment !== name) {
      throw new Error(
        `Catalog line ${line} mismatch: name "${name}" does not match qualified entry "${qualifiedName}".`,
      );
    }

    entries.push({ name, conflictName, packageName });
  }

  return entries;
}

function emitCatalog(
  entries: CatalogEntry[],
  namesText: string,
  qualifiedNamesText: string,
): string {
  const rows = entries
    .map(
      (entry) =>
        `  ${JSON.stringify(entry.name)}: { conflictName: ${JSON.stringify(entry.conflictName)}, packageName: ${JSON.stringify(entry.packageName)} },`,
    )
    .join("\n");

  return `// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated>
// Generated by eng/scripts/generate-azc0034-catalog.ts.
// Source: ${sourceRepository}@${sourceRef}
//   ${reservedNamesPath}
//   ${reservedQualifiedNamesPath}
// reserved-type-names.txt SHA256: ${hash(normalizeNewlines(namesText))}
// reserved-type-qualified-names.txt SHA256: ${hash(normalizeNewlines(qualifiedNamesText))}
// </auto-generated>

// cspell:disable

export interface CSharpReservedTypeNameConflict {
  readonly conflictName: string;
  readonly packageName: string;
}

export const csharpReservedTypeNameConflicts: Record<string, CSharpReservedTypeNameConflict> = {
${rows}
};
`;
}

async function main() {
  const namesUrl = `${sourceBaseUrl}/reserved-type-names.txt`;
  const qualifiedNamesUrl = `${sourceBaseUrl}/reserved-type-qualified-names.txt`;
  const [namesText, qualifiedNamesText] = await Promise.all([
    fetchText(namesUrl),
    fetchText(qualifiedNamesUrl),
  ]);
  const entries = parseCatalog(namesText, qualifiedNamesText);
  const prettierConfig = (await resolveConfig(outputPath)) ?? {};
  const content = await format(emitCatalog(entries, namesText, qualifiedNamesText), {
    ...prettierConfig,
    filepath: outputPath,
    parser: "typescript",
  });

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content, "utf8");
  console.log(`Generated ${entries.length} AZC0034 catalog entries at ${outputPath}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
