emit:
  - "@azure-tools/typespec-autorest"
  - "@typespec/openapi3"
  - "@azure-tools/typespec-python"
options:
  "@azure-tools/typespec-autorest":
    output-file: "{emitter-output-dir}/{service-name}/{version}/openapi.json"
  "@azure-tools/typespec-python":
    namespace: "contoso.benchmarkwidgets"
    package-mode: dataplane
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
