# Continuous Integration

trigger:
  branches:
    include:
      - main
      - release/*
  paths:
    exclude:
      - docs/release-notes/*.md
      - packages/website/versioned_docs/version-latest/release-notes/*.md

pr: none

variables:
  - template: templates/variables/globals.yml

jobs:
  - job: npm_stable
    timeoutInMinutes: 90
    displayName: Npm publish
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022

    variables:
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    steps:
      - checkout: self
        submodules: true

      - template: ./templates/install.yml
        parameters:
          nodeVersion: "20.x"
      - template: ./templates/build.yml

      - script: node common/scripts/install-run-rush.js test-official --parallelism max --verbose
        displayName: Test

      - template: ./templates/upload-coverage.yml

      - script: |
          set NPM_AUTH_TOKEN=$(azure-sdk-npm-token)
          node common/scripts/install-run-rush.js publish --publish --include-all --version-policy typespec-azure --set-access-level public
        displayName: Release

      - task: AzureCLI@1
        displayName: "Publish bundled packages to package storage"
        inputs:
          azureSubscription: "Azure SDK Engineering System"
          scriptLocation: inlineScript
          inlineScript: node ./eng/scripts/upload-bundler-packages.js

      - task: AzureCLI@1
        displayName: "Publish Azure playground"
        inputs:
          azureSubscription: "Azure SDK Engineering System"
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch ^
              --destination $web ^
              --account-name "cadlplayground" ^
              --destination-path cadl-azure/ ^
              --source "./packages/typespec-azure-playground-website/dist/" ^
              --overwrite

  - job: npm_preview
    timeoutInMinutes: 90
    dependsOn: npm_stable
    displayName: Npm publish dev version
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main') # Only publish -dev on main branch.
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022

    variables:
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    steps:
      - checkout: self
        submodules: true

      - template: ./templates/install.yml
        parameters:
          nodeVersion: "20.x"
      - template: ./templates/build.yml

      - script: node ./core/packages/internal-build-utils/cmd/cli.js bump-version-preview . ./core
        displayName: Bump version to prerelease targets

      - script: |
          set NPM_AUTH_TOKEN=$(azure-sdk-npm-token)
          node common/scripts/install-run-rush.js publish --publish --include-all --version-policy typespec-azure --set-access-level public --tag next
        displayName: Release
