trigger: none

resources:
  repositories:
    - repository: azure-rest-api-specs
      type: github
      name: Azure/azure-rest-api-specs
      endpoint: azure

stages:
  - stage: Build_and_Validate
    jobs:
      - job: Validate_generated_swagger
        steps:
        - checkout: self
          submodules: true
        - task: UseDotNet@2
          inputs:
            version: 8.0.x

        - task: NodeTool@0
          inputs:
            versionSpec: 20.x
          displayName: Install Node.js
          retryCountOnTaskFailure: 3

        - script: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
          displayName: Install pnpm
          workingDirectory: $(Build.SourcesDirectory)/typespec-azure

        - script: |
            echo "Node:"
            node -v
            echo "Pnpm:"
            pnpm -v
          displayName: "Log tool versions used"
          workingDirectory: $(Build.SourcesDirectory)/typespec-azure

        # purge before install to ensure a clean state between retries
        - script: pnpm install
          displayName: Install JavaScript Dependencies
          retryCountOnTaskFailure: 3
          workingDirectory: $(Build.SourcesDirectory)/typespec-azure

        - script: dotnet restore core/packages/typespec-vs
          displayName: Restore .NET Dependencies
          workingDirectory: $(Build.SourcesDirectory)/typespec-azure
          
        - script: pnpm run build
          displayName: Build
          workingDirectory: $(Build.SourcesDirectory)/typespec-azure

        - checkout: azure-rest-api-specs
          fetchDepth: 1
        - pwsh: |
            $packageJson = Get-Content -Raw "package.json" | ConvertFrom-Json -AsHashtable

            $packageJson.devDependencies["@azure-tools/typespec-autorest"] = "file:$(Build.SourcesDirectory)/typespec-azure/packages/typespec-autorest"
            $packageJson.devDependencies["@azure-tools/typespec-azure-core"] = "file:$(Build.SourcesDirectory)/typespec-azure/packages/typespec-azure-core"
            $packageJson.devDependencies["@azure-tools/typespec-azure-portal-core"] = "file:$(Build.SourcesDirectory)/typespec-azure/packages/typespec-azure-portal-core"
            $packageJson.devDependencies["@azure-tools/typespec-azure-resource-manager"] = "file:$(Build.SourcesDirectory)/typespec-azure/packages/typespec-azure-resource-manager"
            $packageJson.devDependencies["@azure-tools/typespec-client-generator-core"] = "file:$(Build.SourcesDirectory)/typespec-azure/packages/typespec-client-generator-core"
            $packageJson.devDependencies["@azure-tools/typespec-azure-rulesets"] = "file:$(Build.SourcesDirectory)/typespec-azure/packages/typespec-azure-rulesets"
            $packageJson.devDependencies["@typespec/compiler"] = "file:$(Build.SourcesDirectory)/typespec-azure/core/packages/compiler"
            $packageJson.devDependencies["@typespec/http"] = "file:$(Build.SourcesDirectory)/typespec-azure/core/packages/http"
            $packageJson.devDependencies["@typespec/openapi"] = "file:$(Build.SourcesDirectory)/typespec-azure/core/packages/openapi"
            $packageJson.devDependencies["@typespec/openapi3"] = "file:$(Build.SourcesDirectory)/typespec-azure/core/packages/openapi3"
            $packageJson.devDependencies["@typespec/rest"] = "file:$(Build.SourcesDirectory)/typespec-azure/core/packages/rest"
            $packageJson.devDependencies["@typespec/versioning"] = "file:$(Build.SourcesDirectory)/typespec-azure/core/packages/versioning"

            $packageJson | ConvertTo-Json -Depth 100 | Out-File -Path "package.json" -Encoding utf8 -NoNewline -Force
          displayName: 'Update package.json in azure-rest-api-specs'
          workingDirectory: $(Build.SourcesDirectory)/azure-rest-api-specs
        - script: pnpm install
          displayName: Install updated TypeSpec dependencies
          workingDirectory: $(Build.SourcesDirectory)/azure-rest-api-specs
        - pwsh: ./eng/scripts/TypeSpec-Generate-Swagger.ps1 -CheckAll
          displayName: 'Generate all swagger files'
          workingDirectory: $(Build.SourcesDirectory)/azure-rest-api-specs
        - pwsh: git diff
          displayName: 'Check for changes'
          workingDirectory: $(Build.SourcesDirectory)/azure-rest-api-specs
            
            
