trigger: none
pr:
  - main
  - release/*

variables:
  - template: templates/variables/globals.yml

jobs:
  - job: Build_And_Test
    variables:
      TYPESPEC_VS_CI_BUILD: true # Enable official Visual Studio extension build
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    strategy:
      matrix:
        # Node 18
        "Linux - Node 18.x - Dotnet 6":
          pool: azsdk-pool-mms-ubuntu-2004-general
          imageName: ubuntu-20.04
          nodeVersion: "18.x"
          dotnetVersion: 6.0.x

        "Windows - Node 18.x - Dotnet 6":
          pool: azsdk-pool-mms-win-2022-general
          imageName: windows-2022
          nodeVersion: "18.x"
          dotnetVersion: 6.0.x

        # Node 20
        "Linux - Node 20.x":
          pool: azsdk-pool-mms-ubuntu-2004-general
          imageName: ubuntu-20.04
          nodeVersion: "20.x"
          dotnetVersion: 6.0.x

        "Windows - Node 20.x":
          pool: azsdk-pool-mms-win-2022-general
          imageName: windows-2022
          nodeVersion: "20.x"
          dotnetVersion: 6.0.x

    pool:
      name: $(pool)
      vmImage: $(imageName)

    steps:
      - template: ./jobs/build-and-test.yml
        parameters:
          nodeVersion: $(nodeVersion)
          dotnetVersion: $(dotnetVersion)
          poolName: $(pool)

      - template: ./templates/swagger-checks.yml
        parameters:
          nodeVersion: $(nodeVersion)

  - job: Consistency_Check
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: ubuntu-20.04

    steps:
      - template: ./jobs/pull-request-consistency.yml

  - template: e2e-job.yml
  - template: jobs/publish-artifacts.yml
