# Continuous Integration

trigger:
  branches:
    include:
      - main
      - release/*
      - esrp-publish # TODO: for test remove

  paths:
    exclude:
      - docs/release-notes/*.md
      - packages/website/versioned_docs/version-latest/release-notes/*.md

pr: none

extends:
  template: /eng/pipelines/templates/1es-redirect.yml
  parameters:
    variables:
      - template: /eng/pipelines/templates/variables/globals.yml@self
    stages:
      - stage: build
        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux
        jobs:
          - template: /eng/pipelines/jobs/build-for-publish.yml@self

      - stage: publish_npm
        displayName: Publish Npm Packages
        dependsOn: build
        condition: or(eq('true', dependencies.build.outputs['build.pack_npm_packages_stable.PUBLISH_PKG_ANY']), eq('true', dependencies.build.outputs['build.pack_npm_packages_next.PUBLISH_PKG_ANY']))

        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux

        jobs:
          - template: /eng/pipelines/jobs/publish-npm.yml
            parameters:
              artifactName: npm-packages-stable
              tag: latest
              condition: eq('true', stageDependencies.build.build.outputs['pack_npm_packages_stable.PUBLISH_PKG_ANY'])

          - template: /eng/pipelines/jobs/publish-npm.yml
            parameters:
              dependsOn: publish_npm_latest
              artifactName: npm-packages-next
              tag: next
              condition: eq('true', stageDependencies.build.build.outputs['pack_npm_packages_next.PUBLISH_PKG_ANY'])

          - template: /eng/pipelines/jobs/create-github-release.yml
            parameters:
              dependsOn: publish_npm_latest
              artifactName: npm-packages-stable
