import type { Children } from "@alloy-js/core";
import { code } from "@alloy-js/core";
import { d } from "@alloy-js/core/testing";
import * as ts from "@alloy-js/typescript";
import type { Program } from "@typespec/compiler";
import { Output } from "@typespec/emitter-framework";
import * as ef from "@typespec/emitter-framework/typescript";
import { beforeAll, describe, expect, it } from "vitest";
import { buildServerModel } from "../src/build-model.js";
import type { ServerModel } from "../src/model.js";
import { GeneratedSourceFile } from "../src/render/generated-source-file.js";
import {
  contextRefkey,
  modelXmlMetadataRefkey,
  operationMetadataRefkey,
  operationParametersRefkey,
  operationResponseRefkey,
} from "../src/render/refkeys.js";
import { ServiceHandlerInterface } from "../src/render/render-handlers.js";
import { operationDescriptorValue, renderMetadata } from "../src/render/render-metadata.js";
import { renderModels } from "../src/render/render-models.js";
import { renderOperations } from "../src/render/render-operations.js";
import { renderSerialization } from "../src/render/render-serialization.js";
import { createRuntimeSymbols } from "../src/render/runtime-symbols.js";
import { ApiTester } from "./tester.js";

let testProgram: Program;
let sampleServerModel: ServerModel;
const runtimeSymbols = createRuntimeSymbols("../runtime/serializationRuntime");

beforeAll(async () => {
  const { program } = await ApiTester.compile({
    "main.tsp": `
      import "@typespec/http";
      using Http;

      @service
      namespace RenderTest;

      @doc("Queue metadata.")
      model QueueMetadata {
        @doc("A description.")
        description?: string;
        publicAccess?: boolean;
        tags?: string[];
        metadata?: Record<string>;
      }

      model QueueMessage {
        messageId: string;
        metadata: QueueMetadata;
        tags?: string[];
      }

      @route("/{queueName}")
      interface Queue {
        @doc("Creates a queue.")
        @put
        op CreateQueue(@path queueName: string, @body body: string): {
          @statusCode statusCode: 201;
          @header("x-ms-request-id") requestId: string;
        };

        @delete
        op DeleteQueue(@path queueName: string): {
          @statusCode statusCode: 204;
          @header("x-ms-request-id") requestId: string;
        };

        @get
        @route("/metadata")
        op GetMetadata(@path queueName: string): {
          @statusCode statusCode: 200;
          @body body: QueueMetadata;
        };

        @get
        @route("/message")
        op GetMessage(@path queueName: string): {
          @statusCode statusCode: 200;
          @body body: QueueMessage;
        };
      }
    `,
  });
  testProgram = program;
  const builtModel = buildServerModel(program);
  sampleServerModel = {
    ...builtModel,
    models: builtModel.models.filter((model) =>
      ["QueueMetadata", "QueueMessage"].includes(model.name),
    ),
    operations: builtModel.operations.filter((operation) =>
      ["CreateQueue", "DeleteQueue"].includes(operation.name),
    ),
  };
});

function Wrapper(props: { children: Children }) {
  return (
    <Output program={testProgram} externals={[runtimeSymbols]}>
      {props.children}
    </Output>
  );
}

function SourceFile(props: { children: Children }) {
  return (
    <Wrapper>
      <ts.SourceFile path="test.ts">{props.children}</ts.SourceFile>
    </Wrapper>
  );
}

describe("renderModels", () => {
  it("renders a generated source file header before synthesized imports", () => {
    expect(
      <Wrapper>
        <GeneratedSourceFile path="test.ts">
          <ts.VarDeclaration
            const
            name="runtime"
            initializer={
              <>
                <ts.Reference refkey={runtimeSymbols.createSerializationRuntime} />
                (metadata)
              </>
            }
          />
        </GeneratedSourceFile>
      </Wrapper>,
    ).toRenderTo({
      "test.ts": d`
        // This file was automatically generated by @azure-tools/typespec-azurite-emitter.
        // Do not edit this file manually; re-run \`tsp compile\` to regenerate it.


        import { createSerializationRuntime } from "../runtime/serializationRuntime";

        const runtime = createSerializationRuntime(metadata)
      `,
    });
  });

  it("renders TypeScript interfaces for server data models", () => {
    expect(<Wrapper>{renderModels(sampleServerModel, runtimeSymbols)}</Wrapper>).toRenderTo(`
      // This file was automatically generated by @azure-tools/typespec-azurite-emitter.
      // Do not edit this file manually; re-run \`tsp compile\` to regenerate it.


      import { defineXmlModel } from "../runtime/serializationRuntime";

      /**
       * Queue metadata.
       */
      export interface QueueMetadata {
        /**
         * A description.
         */
        description?: string;
        publicAccess?: boolean;
        tags?: Array<string>;
        metadata?: Record<string, string>;
      }
      export const QueueMetadataXmlMetadata = defineXmlModel("QueueMetadata", [
        "QueueMetadata",
        [
          ["description", "description", "string"],
          ["publicAccess", "publicAccess", "boolean"],
          ["tags", "tags", ["array", "string"], undefined, "tags"],
          ["metadata", "metadata", ["record", "string"]]
        ]
      ])
      export interface QueueMessage {
        messageId: string;
        metadata: QueueMetadata;
        tags?: Array<string>;
      }
      export const QueueMessageXmlMetadata = defineXmlModel("QueueMessage", [
        "QueueMessage",
        [
          ["messageId", "messageId", "string", undefined, undefined, true],
          [
            "metadata",
            "metadata",
            ["model", "QueueMetadata"],
            undefined,
            undefined,
            true
          ],
          ["tags", "tags", ["array", "string"], undefined, "tags"]
        ]
      ])
    `);
  });
});

describe("renderOperations", () => {
  it("renders operation declarations only", () => {
    expect(<Wrapper>{renderOperations(sampleServerModel, runtimeSymbols)}</Wrapper>).toRenderTo(`
      // This file was automatically generated by @azure-tools/typespec-azurite-emitter.
      // Do not edit this file manually; re-run \`tsp compile\` to regenerate it.


      import { defineOperation } from "../runtime/serializationRuntime";

      /**
       * Creates a queue.
       */
      export interface CreateQueueParameters {
        queueName: string;
        body: string;
      }
      export type CreateQueueResponse = {
        statusCode: 201;
        headers: {
          requestId: string;
        };
      };
      export const CreateQueueMetadata = defineOperation([
        "CreateQueue",
        "put",
        "/{queueName}",
        [["queueName", "queueName", "path", "string", true]],
        ["string", ["text/plain"]],
        [[201, [["requestId", "x-ms-request-id", "string"]]]],
        "Queue"
      ])

      export interface DeleteQueueParameters {
        queueName: string;
      }
      export type DeleteQueueResponse = {
        statusCode: 204;
        headers: {
          requestId: string;
        };
      };
      export const DeleteQueueMetadata = defineOperation([
        "DeleteQueue",
        "delete",
        "/{queueName}",
        [["queueName", "queueName", "path", "string", true]],
        undefined,
        [[204, [["requestId", "x-ms-request-id", "string"]]]],
        "Queue"
      ])

    `);
  });

  it("renders compact operation descriptor values with Alloy recursive value expressions", () => {
    expect(
      <SourceFile>
        <ts.ValueExpression jsValue={operationDescriptorValue(sampleServerModel.operations[0])} />
      </SourceFile>,
    ).toRenderTo(`
      [
        "CreateQueue",
        "put",
        "/{queueName}",
        [["queueName", "queueName", "path", "string", true]],
        ["string", ["text/plain"]],
        [[201, [["requestId", "x-ms-request-id", "string"]]]],
        "Queue"
      ]
    `);
  });
});

describe("ServiceHandlerInterface", () => {
  it("renders handler methods with automatic cross-file imports from refkeys", () => {
    expect(
      <Wrapper>
        <ts.SourceFile path="operations.ts">
          <ts.InterfaceDeclaration
            export
            name="CreateQueueParameters"
            refkey={operationParametersRefkey(sampleServerModel.operations[0])}
          />
          <ts.TypeDeclaration
            export
            name="CreateQueueResponse"
            refkey={operationResponseRefkey(sampleServerModel.operations[0])}
          >
            {code`{ statusCode: 201 }`}
          </ts.TypeDeclaration>
          <ts.InterfaceDeclaration
            export
            name="DeleteQueueParameters"
            refkey={operationParametersRefkey(sampleServerModel.operations[1])}
          />
          <ts.TypeDeclaration
            export
            name="DeleteQueueResponse"
            refkey={operationResponseRefkey(sampleServerModel.operations[1])}
          >
            {code`{ statusCode: 204 }`}
          </ts.TypeDeclaration>
        </ts.SourceFile>
        <ts.SourceFile path="handlers.ts">
          <ef.InterfaceDeclaration export name="Context" refkey={contextRefkey}>
            <ts.InterfaceMember readonly name="contextId" type={code`string`} />
            {code`;`}
          </ef.InterfaceDeclaration>
          <hbr />
          <ServiceHandlerInterface serverModel={sampleServerModel} />
        </ts.SourceFile>
      </Wrapper>,
    ).toRenderTo({
      "operations.ts": d`
              export interface CreateQueueParameters {

              }export type CreateQueueResponse = { statusCode: 201 };export interface DeleteQueueParameters {

              }export type DeleteQueueResponse = { statusCode: 204 };
            `,
      "handlers.ts": d`
              import type {
                CreateQueueParameters,
                CreateQueueResponse,
                DeleteQueueParameters,
                DeleteQueueResponse,
              } from "./operations.js";

              export interface Context {
                readonly contextId: string;
              }
              export interface IServiceHandler {
                /**
                 * Creates a queue.
                 *
                 * @param {CreateQueueParameters} params
                 * @param {Context} context
                 */
                createQueue(
                  params: CreateQueueParameters,
                  context: Context,
                ): Promise<CreateQueueResponse>;
                deleteQueue(
                  params: DeleteQueueParameters,
                  context: Context,
                ): Promise<DeleteQueueResponse>;
              }
            `,
    });
  });
});

describe("renderMetadata", () => {
  it("renders one consolidated service metadata manifest", () => {
    expect(
      <Wrapper>
        <ts.SourceFile path="models.ts">
          <ts.VarDeclaration
            export
            const
            name="QueueMetadataXmlMetadata"
            refkey={modelXmlMetadataRefkey(sampleServerModel.models[0])}
          />
          <ts.VarDeclaration
            export
            const
            name="QueueMessageXmlMetadata"
            refkey={modelXmlMetadataRefkey(sampleServerModel.models[1])}
          />
        </ts.SourceFile>
        <ts.SourceFile path="operations.ts">
          <ts.VarDeclaration
            export
            const
            name="CreateQueueMetadata"
            refkey={operationMetadataRefkey(sampleServerModel.operations[0])}
          />
          <ts.VarDeclaration
            export
            const
            name="DeleteQueueMetadata"
            refkey={operationMetadataRefkey(sampleServerModel.operations[1])}
          />
        </ts.SourceFile>
        {renderMetadata(sampleServerModel, "../runtime/serializationRuntime", runtimeSymbols)}
      </Wrapper>,
    ).toRenderTo({
      "metadata.ts": d`
        // This file was automatically generated by @azure-tools/typespec-azurite-emitter.
        // Do not edit this file manually; re-run \`tsp compile\` to regenerate it.


        import {
          defineServiceMetadata,
          type OperationMetadata,
          type ServiceMetadata,
        } from "../runtime/serializationRuntime";

        import { QueueMetadataXmlMetadata, QueueMessageXmlMetadata } from "./models";
        import { CreateQueueMetadata, DeleteQueueMetadata } from "./operations";

        export type { OperationMetadata, ServiceMetadata } from "../runtime/serializationRuntime";
        export const serviceMetadata: ServiceMetadata = defineServiceMetadata({ operations: [CreateQueueMetadata, DeleteQueueMetadata], xmlModels: [QueueMetadataXmlMetadata, QueueMessageXmlMetadata] });

        export const operations: readonly OperationMetadata[] = serviceMetadata.operations;
      `,
      "models.ts": d`
        export const QueueMetadataXmlMetadataexport const QueueMessageXmlMetadata
      `,
      "operations.ts": d`
        export const CreateQueueMetadataexport const DeleteQueueMetadata
      `,
    });
  });
});

describe("renderSerialization components", () => {
  it("renders thin serialization binding to the configured runtime", () => {
    expect(<Wrapper>{renderSerialization(sampleServerModel, runtimeSymbols)}</Wrapper>).toRenderTo(`
      // This file was automatically generated by @azure-tools/typespec-azurite-emitter.
      // Do not edit this file manually; re-run \`tsp compile\` to regenerate it.


      import { createSerializationRuntime } from "../runtime/serializationRuntime";

      import { serviceMetadata } from "./metadata";

      const runtime = createSerializationRuntime(serviceMetadata);

      export const deserializeRequest = runtime.deserializeRequest;
      export const serializeResponse = runtime.serializeResponse;
      export const hasGeneratedSerialization = runtime.hasGeneratedSerialization;
    `);
  });
});
