import type { Children } from "@alloy-js/core";
import { code } from "@alloy-js/core";
import { d } from "@alloy-js/core/testing";
import * as ts from "@alloy-js/typescript";
import type { Program } from "@typespec/compiler";
import { Output } from "@typespec/emitter-framework";
import * as ef from "@typespec/emitter-framework/typescript";
import { beforeAll, describe, expect, it } from "vitest";
import { buildServerModel } from "../src/build-model.js";
import type { ServerModel } from "../src/model.js";
import {
  contextRefkey,
  operationParametersRefkey,
  operationResponseRefkey,
} from "../src/render/refkeys.js";
import { ServiceHandlerInterface } from "../src/render/render-handlers.js";
import { renderModels } from "../src/render/render-models.js";
import { operationMetadataValue, renderOperations } from "../src/render/render-operations.js";
import {
  DeserializeRequest,
  HasGeneratedSerialization,
  SerializeResponse,
  XmlModelMetadata,
} from "../src/render/render-serialization.js";
import { ApiTester } from "./tester.js";

let testProgram: Program;
let sampleServerModel: ServerModel;
let supportedOperations: ServerModel["operations"];

beforeAll(async () => {
  const { program } = await ApiTester.compile({
    "main.tsp": `
      import "@typespec/http";
      using Http;

      @service
      namespace RenderTest;

      @doc("Queue metadata.")
      model QueueMetadata {
        @doc("A description.")
        description?: string;
        publicAccess?: boolean;
      }

      model QueueMessage {
        messageId: string;
        tags?: string[];
      }

      @route("/{queueName}")
      interface Queue {
        @doc("Creates a queue.")
        @put
        op CreateQueue(@path queueName: string, @body body: string): {
          @statusCode statusCode: 201;
          @header("x-ms-request-id") requestId: string;
        };

        @delete
        op DeleteQueue(@path queueName: string): {
          @statusCode statusCode: 204;
          @header("x-ms-request-id") requestId: string;
        };

        @get
        @route("/metadata")
        op GetMetadata(@path queueName: string): {
          @statusCode statusCode: 200;
          @body body: QueueMetadata;
        };

        @get
        @route("/message")
        op GetMessage(@path queueName: string): {
          @statusCode statusCode: 200;
          @body body: QueueMessage;
        };
      }
    `,
  });
  testProgram = program;
  const builtModel = buildServerModel(program);
  sampleServerModel = {
    ...builtModel,
    models: builtModel.models.filter((model) =>
      ["QueueMetadata", "QueueMessage"].includes(model.name),
    ),
    operations: builtModel.operations.filter((operation) =>
      ["CreateQueue", "DeleteQueue"].includes(operation.name),
    ),
  };
  supportedOperations = sampleServerModel.operations;
});

function Wrapper(props: { children: Children }) {
  return <Output program={testProgram}>{props.children}</Output>;
}

function SourceFile(props: { children: Children }) {
  return (
    <Wrapper>
      <ts.SourceFile path="test.ts">{props.children}</ts.SourceFile>
    </Wrapper>
  );
}

describe("renderModels", () => {
  it("renders TypeScript interfaces for server data models", () => {
    expect(<Wrapper>{renderModels(sampleServerModel)}</Wrapper>).toRenderTo(`
      // This file was automatically generated by @azure-tools/typespec-azurite-emitter.
      // Do not edit this file manually; re-run \`tsp compile\` to regenerate it.
      /**
       * Queue metadata.
       */
      export interface QueueMetadata {
        /**
         * A description.
         */
        description?: string;
        publicAccess?: boolean;
      }
      export interface QueueMessage {
        messageId: string;
        tags?: Array<string>;
      }
    `);
  });
});

describe("renderOperations", () => {
  it("renders operation declarations and metadata", () => {
    expect(<Wrapper>{renderOperations(sampleServerModel)}</Wrapper>).toRenderTo(`
      // This file was automatically generated by @azure-tools/typespec-azurite-emitter.
      // Do not edit this file manually; re-run \`tsp compile\` to regenerate it.
      /**
       * Creates a queue.
       */
      export interface CreateQueueParameters {
        queueName: string;
        body: string;
      }
      export type CreateQueueResponse = {
        statusCode: 201;
        headers: {
          requestId: string;
        };
      };

      export interface DeleteQueueParameters {
        queueName: string;
      }
      export type DeleteQueueResponse = {
        statusCode: 204;
        headers: {
          requestId: string;
        };
      };
      export type OperationTypeBinding = {
        kind: "string" | "number" | "boolean" | "datetime" | "unknown";
      } | {
        kind: "model";
        name: string;
      } | {
        kind: "literal";
        value: string | number | boolean;
      } | {
        kind: "array";
        element: OperationTypeBinding;
      } | {
        kind: "record";
        element: OperationTypeBinding;
      } | {
        kind: "union";
        variants: Array<OperationTypeBinding>;
      };
      export interface OperationParameterBinding {
        readonly name: string;
        readonly wireName: string;
        readonly location: "path" | "query" | "header";
        readonly required: boolean;
        readonly type: OperationTypeBinding;
      }
      export interface OperationResponseHeaderBinding {
        readonly name: string;
        readonly wireName: string;
        readonly type: OperationTypeBinding;
      }
      export interface OperationResponseMetadata {
        readonly statusCode: number | "*";
        readonly headers: readonly OperationResponseHeaderBinding[];
        readonly body?: {
          readonly type: OperationTypeBinding;
        };
      }
      export interface OperationLiteralQueryParameter {
        readonly name: string;
        readonly value: string;
      }
      export interface OperationMetadata {
        readonly name: string;
        readonly verb: string;
        readonly rawPath: string;
        readonly path: string;
        readonly literalQueryParameters: readonly OperationLiteralQueryParameter[];
        readonly requiredQueryParameters: readonly string[];
        readonly requiredHeaderParameters: readonly string[];
        readonly parameters: readonly OperationParameterBinding[];
        readonly hasRequestBody: boolean;
        readonly requestBodyContentTypes: readonly string[];
        readonly requestBodyParameterPath?: string | readonly string[];
        readonly requestBodyType?: OperationTypeBinding;
        readonly responses: readonly OperationResponseMetadata[];
        readonly interfaceName?: string;
      }
      export const operations: readonly OperationMetadata[] = [
        {
          name: "CreateQueue",
          verb: "put",
          rawPath: "/{queueName}",
          path: "/{queueName}",
          literalQueryParameters: [],
          requiredQueryParameters: [],
          requiredHeaderParameters: [],
          parameters: [
            {
              name: "queueName",
              wireName: "queueName",
              location: "path",
              required: true,
              type: {
                kind: "string",
              },
            }
          ],
          hasRequestBody: true,
          requestBodyContentTypes: ["text/plain"],
          requestBodyParameterPath: "body",
          requestBodyType: {
            kind: "string",
          },
          responses: [
            {
              statusCode: 201,
              headers: [
                {
                  name: "requestId",
                  wireName: "x-ms-request-id",
                  type: {
                    kind: "string",
                  },
                }
              ],
            }
          ],
          interfaceName: "Queue",
        },
        {
          name: "DeleteQueue",
          verb: "delete",
          rawPath: "/{queueName}",
          path: "/{queueName}",
          literalQueryParameters: [],
          requiredQueryParameters: [],
          requiredHeaderParameters: [],
          parameters: [
            {
              name: "queueName",
              wireName: "queueName",
              location: "path",
              required: true,
              type: {
                kind: "string",
              },
            }
          ],
          hasRequestBody: false,
          requestBodyContentTypes: [],
          responses: [
            {
              statusCode: 204,
              headers: [
                {
                  name: "requestId",
                  wireName: "x-ms-request-id",
                  type: {
                    kind: "string",
                  },
                }
              ],
            }
          ],
          interfaceName: "Queue",
        }
      ]
    `);
  });

  it("renders operation metadata values with Alloy recursive value expressions", () => {
    expect(
      <SourceFile>
        <ts.ValueExpression jsValue={operationMetadataValue(sampleServerModel.operations[0])} />
      </SourceFile>,
    ).toRenderTo(`
      {
        name: "CreateQueue",
        verb: "put",
        rawPath: "/{queueName}",
        path: "/{queueName}",
        literalQueryParameters: [],
        requiredQueryParameters: [],
        requiredHeaderParameters: [],
        parameters: [
          {
            name: "queueName",
            wireName: "queueName",
            location: "path",
            required: true,
            type: {
              kind: "string",
            },
          }
        ],
        hasRequestBody: true,
        requestBodyContentTypes: ["text/plain"],
        requestBodyParameterPath: "body",
        requestBodyType: {
          kind: "string",
        },
        responses: [
          {
            statusCode: 201,
            headers: [
              {
                name: "requestId",
                wireName: "x-ms-request-id",
                type: {
                  kind: "string",
                },
              }
            ],
          }
        ],
        interfaceName: "Queue",
      }
    `);
  });
});

describe("ServiceHandlerInterface", () => {
  it("renders handler methods with automatic cross-file imports from refkeys", () => {
    expect(
      <Wrapper>
        <ts.SourceFile path="operations.ts">
          <ts.InterfaceDeclaration
            export
            name="CreateQueueParameters"
            refkey={operationParametersRefkey(sampleServerModel.operations[0])}
          />
          <ts.TypeDeclaration
            export
            name="CreateQueueResponse"
            refkey={operationResponseRefkey(sampleServerModel.operations[0])}
          >
            {code`{ statusCode: 201 }`}
          </ts.TypeDeclaration>
          <ts.InterfaceDeclaration
            export
            name="DeleteQueueParameters"
            refkey={operationParametersRefkey(sampleServerModel.operations[1])}
          />
          <ts.TypeDeclaration
            export
            name="DeleteQueueResponse"
            refkey={operationResponseRefkey(sampleServerModel.operations[1])}
          >
            {code`{ statusCode: 204 }`}
          </ts.TypeDeclaration>
        </ts.SourceFile>
        <ts.SourceFile path="handlers.ts">
          <ef.InterfaceDeclaration export name="Context" refkey={contextRefkey}>
            <ts.InterfaceMember readonly name="contextId" type={code`string`} />
            {code`;`}
          </ef.InterfaceDeclaration>
          <hbr />
          <ServiceHandlerInterface serverModel={sampleServerModel} />
        </ts.SourceFile>
      </Wrapper>,
    ).toRenderTo({
      "operations.ts": d`
              export interface CreateQueueParameters {

              }export type CreateQueueResponse = { statusCode: 201 };export interface DeleteQueueParameters {

              }export type DeleteQueueResponse = { statusCode: 204 };
            `,
      "handlers.ts": d`
              import type {
                CreateQueueParameters,
                CreateQueueResponse,
                DeleteQueueParameters,
                DeleteQueueResponse,
              } from "./operations.js";

              export interface Context {
                readonly contextId: string;
              }
              export interface IServiceHandler {
                /**
                 * Creates a queue.
                 *
                 * @param {CreateQueueParameters} params
                 * @param {Context} context
                 */
                createQueue(
                  params: CreateQueueParameters,
                  context: Context,
                ): Promise<CreateQueueResponse>;
                deleteQueue(
                  params: DeleteQueueParameters,
                  context: Context,
                ): Promise<DeleteQueueResponse>;
              }
            `,
    });
  });
});

describe("renderSerialization components", () => {
  it("renders XML model metadata from Alloy object/value components", () => {
    expect(
      <SourceFile>
        <XmlModelMetadata models={sampleServerModel.models} />
      </SourceFile>,
    ).toRenderTo(`
      interface XmlPropertyMetadata {
        readonly name: string;
        readonly wireName: string;
        readonly type: OperationTypeBinding;
        readonly attribute: boolean;
        readonly unwrapped: boolean;
        readonly itemName?: string;
      }

      interface XmlModelMetadata {
        readonly name: string;
        readonly wireName: string;
        readonly properties: readonly XmlPropertyMetadata[];
      }

      const xmlModels: Record<string, XmlModelMetadata> ={
        QueueMetadata: {
          name: "QueueMetadata",
          wireName: "QueueMetadata",
          properties: [
            {
              name: "description",
              wireName: "description",
              type: {
                kind: "string",
              },
              attribute: false,
              unwrapped: false,
            },
            {
              name: "publicAccess",
              wireName: "publicAccess",
              type: {
                kind: "boolean",
              },
              attribute: false,
              unwrapped: false,
            }
          ],
        },
        QueueMessage: {
          name: "QueueMessage",
          wireName: "QueueMessage",
          properties: [
            {
              name: "messageId",
              wireName: "messageId",
              type: {
                kind: "string",
              },
              attribute: false,
              unwrapped: false,
            },
            {
              name: "tags",
              wireName: "tags",
              type: {
                kind: "array",
                element: {
                  kind: "string",
                },
              },
              attribute: false,
              unwrapped: false,
              itemName: "tags",
            }
          ],
        },
      };
    `);
  });

  it("renders serialization entrypoint declarations with metadata lookups", () => {
    expect(
      <SourceFile>
        <DeserializeRequest operations={supportedOperations} />
        <hbr />
        <SerializeResponse operations={supportedOperations} />
        <hbr />
        <HasGeneratedSerialization operations={supportedOperations} />
      </SourceFile>,
    ).toRenderTo(`
      export async function deserializeRequest(
        name: string,
        req: IRequest,
        context: Context,
      ): Promise<IHandlerParameters | undefined> {
        const metadata = getGeneratedOperation(name);
        return metadata === undefined ? undefined : deserializeMetadataRequest(metadata, req, context);
      }
      export function serializeResponse(
        name: string,
        res: IResponse,
        handlerResponse: any,
      ): boolean {
        const metadata = getGeneratedOperation(name);
        if (metadata === undefined) return false;
        serializeMetadataResponse(metadata, res, handlerResponse);
        return true;
      }
      export function hasGeneratedSerialization(name: string): boolean {
        return generatedOperationNames.has(name);
      }
    `);
  });
});
