// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package example

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strings"
)

// ContentNegotiationSameBodySingleOperationClient contains the methods for the ContentNegotiationSameBodySingleOperation
// group.
// Don't use this type directly, use [ContentNegotiationClient.NewContentNegotiationSameBodySingleOperationClient] instead.
type ContentNegotiationSameBodySingleOperationClient struct {
	internal *azcore.Client
	endpoint string
}

// GetAvatar -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - ContentNegotiationSameBodySingleOperationClientGetAvatarOptions contains the optional parameters for the ContentNegotiationSameBodySingleOperationClient.GetAvatar
//     method.
func (client *ContentNegotiationSameBodySingleOperationClient) GetAvatar(ctx context.Context, formatParam string, accept GetAvatarContentType, options *ContentNegotiationSameBodySingleOperationClientGetAvatarOptions) (ContentNegotiationSameBodySingleOperationClientGetAvatarResponse, error) {
	var err error
	req, err := client.getAvatarCreateRequest(ctx, formatParam, accept, options)
	if err != nil {
		return ContentNegotiationSameBodySingleOperationClientGetAvatarResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return ContentNegotiationSameBodySingleOperationClientGetAvatarResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return ContentNegotiationSameBodySingleOperationClientGetAvatarResponse{}, err
	}
	resp, err := client.getAvatarHandleResponse(httpResp)
	return resp, err
}

// getAvatarCreateRequest creates the GetAvatar request.
func (client *ContentNegotiationSameBodySingleOperationClient) getAvatarCreateRequest(ctx context.Context, formatParam string, accept GetAvatarContentType, _ *ContentNegotiationSameBodySingleOperationClientGetAvatarOptions) (*policy.Request, error) {
	urlPath := "/content-negotiation/same-body-single-operation/{format}"
	if formatParam == "" {
		return nil, errors.New("parameter formatParam cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{format}", url.PathEscape(formatParam))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{string(accept)}
	return req, nil
}

// getAvatarHandleResponse handles the GetAvatar response.
func (client *ContentNegotiationSameBodySingleOperationClient) getAvatarHandleResponse(resp *http.Response) (ContentNegotiationSameBodySingleOperationClientGetAvatarResponse, error) {
	result := ContentNegotiationSameBodySingleOperationClientGetAvatarResponse{Body: resp.Body}
	if val := resp.Header.Get("content-type"); val != "" {
		result.ContentType = &val
	}
	return result, nil
}

