// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package example

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// ContentNegotiationClient contains the methods for the ContentNegotiation group.
// Don't use this type directly, use NewContentNegotiationClientWithNoCredential() instead.
type ContentNegotiationClient struct {
	internal *azcore.Client
	endpoint string
}

// ContentNegotiationClientOptions contains the optional values for creating a [ContentNegotiationClient].
type ContentNegotiationClientOptions struct {
	azcore.ClientOptions
}

// NewContentNegotiationClientWithNoCredential creates a new instance of ContentNegotiationClient with the specified values.
//   - endpoint - Service host
//   - options - Contains optional client configuration. Pass nil to accept the default values.
func NewContentNegotiationClientWithNoCredential(endpoint string, options *ContentNegotiationClientOptions) (*ContentNegotiationClient, error) {
	if options == nil {
		options = &ContentNegotiationClientOptions{}
	}
	cl, err := azcore.NewClient(moduleName, moduleVersion, runtime.PipelineOptions{}, &options.ClientOptions)
	if err != nil {
		return nil, err
	}
	client := &ContentNegotiationClient{
		endpoint: endpoint,
	internal: cl,
	}
	return client, nil
}

// NewContentNegotiationSameBodySingleOperationClient creates a new instance of [ContentNegotiationSameBodySingleOperationClient].
func (client *ContentNegotiationClient) NewContentNegotiationSameBodySingleOperationClient() *ContentNegotiationSameBodySingleOperationClient {
	return &ContentNegotiationSameBodySingleOperationClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

