// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package example

// ContentNegotiationSameBodySingleOperationClientGetAvatarOptions contains the optional parameters for the ContentNegotiationSameBodySingleOperationClient.GetAvatar
// method.
type ContentNegotiationSameBodySingleOperationClientGetAvatarOptions struct {
	// placeholder for future optional parameters
}

