// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package example

import "io"

// ContentNegotiationSameBodySingleOperationClientGetAvatarResponse contains the response from method ContentNegotiationSameBodySingleOperationClient.GetAvatar.
type ContentNegotiationSameBodySingleOperationClientGetAvatarResponse struct {
// Body contains the streaming response.
	Body io.ReadCloser
	ContentType *string
}

