emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.ResourceManager.{{parameters.ServiceNamespace}}"
    clear-output-folder: true
    model-namespace: false
    namespace: "{package-dir}"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-{{#toLowerCase}}{{parameters.ServiceNamespace}}{{/toLowerCase}}"
    namespace: "azure.mgmt.{{#toLowerCase}}{{parameters.ServiceNamespace}}{{/toLowerCase}}"
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-{{#toLowerCase}}{{parameters.ServiceNamespace}}{{/toLowerCase}}"
    namespace: "com.azure.resourcemanager.{{#toLowerCase}}{{parameters.ServiceNamespace}}{{/toLowerCase}}"
    service-name: "{{#toLowerCase}}{{parameters.ServiceNamespace}}{{/toLowerCase}}"
  "@azure-tools/typespec-ts":
    package-dir: "arm-{{#toLowerCase}}{{parameters.ServiceNamespace}}{{/toLowerCase}}"
    experimental-extensible-enums: true
    flavor: azure
    package-details:
      name: "@azure/{package-dir}"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/{{#toLowerCase}}{{parameters.ServiceNamespace}}{{/toLowerCase}}"
    package-dir: "arm{{#toLowerCase}}{{parameters.ServiceNamespace}}{{/toLowerCase}}"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
