emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-csharp":
    package-dir: "{package-name}"
    clear-output-folder: true
    model-namespace: false
    namespace: "{package-dir}"
  "@azure-tools/typespec-python":
    package-dir: "{package-dir}"
    package-name: "{package-name}"
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-java":
    package-dir: "{package-dir}"
    namespace: "{namespace}"
    service-name: "{service-name}"
  "@azure-tools/typespec-ts":
    package-dir: "arm-{name}"
    azureSdkForJs: true
    isModularLibrary: true
    generateMetadata: true
    hierarchyClient: false
    experimentalExtensibleEnums: true
    enableOperationGroup: true
    packageDetails:
      name: "@azure/{package-dir}"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/{{normalizePackageName}}"
    package-dir: "arm{{normalizePackageName}}"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    generate-examples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
