parameters:
  - name: nodeVersion
    type: string

steps:
  - checkout: self
    submodules: true

  - template: /eng/pipelines/templates/install.yml
    parameters:
      nodeVersion: ${{ parameters.nodeVersion }}

  - script: pnpm --filter "@typespec/internal-build-utils..." run build
    displayName: Build internal tools

  - script: npm install -g autorest && cd eng/scripts && npm install
    displayName: Swagger - Install Dependencies
  - script: node eng/scripts/lint-resourcemanager.js "packages/samples/test/output/azure/resource-manager"
    displayName: Swagger - Resource Manager Linting
  - script: node eng/scripts/gen-sdk.js python "packages/samples/test/output/azure/resource-manager"
    displayName: Swagger - Generate Python SDK
  - script: node eng/scripts/gen-sdk.js javascript "packages/samples/test/output/azure/resource-manager"
    displayName: Swagger - Generate JavaScript SDK
