parameters:
  - name: nodeVersion
    type: string

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.nodeVersion }}
    displayName: Install Node.js
    retryCountOnTaskFailure: 3

  - script: npm install -g autorest && cd eng/scripts && npm install
    displayName: Swagger - Install Dependencies
  - script: node eng/scripts/lint-resourcemanager.js "packages/samples/test/output/azure/resource-manager"
    displayName: Swagger - Resource Manager Linting
  - script: node eng/scripts/gen-sdk.js python "packages/samples/test/output/azure/resource-manager"
    displayName: Swagger - Generate Python SDK
  - script: node eng/scripts/gen-sdk.js javascript "packages/samples/test/output/azure/resource-manager"
    displayName: Swagger - Generate JavaScript SDK
