jobs:
  - job: build
    displayName: Build Packages

    variables:
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    steps:
      - checkout: self
        submodules: true

      - template: /eng/pipelines/templates/install.yml

      - template: /eng/pipelines/templates/build.yml

      - script: pnpm run test:ci
        displayName: Test

      - template: /eng/pipelines/templates/upload-coverage.yml
      - template: /eng/pipelines/templates/pack.yml
        parameters:
          artifactName: npm-packages-stable
          name: npm_packages_stable

      - task: AzureCLI@1
        displayName: "Publish bundled packages to package storage"
        inputs:
          azureSubscription: "Azure SDK Engineering System"
          scriptLocation: inlineScript
          inlineScript: node ./eng/scripts/upload-bundler-packages.js

      - task: AzureCLI@2
        displayName: Upload scenario manifest
        condition: eq(variables['PUBLISH_PKG_AZURE_TOOLS_AZURE_HTTP_SPECS'], 'true')
        inputs:
          workingDirectory: packages/azure-http-specs
          azureSubscription: "TypeSpec Storage"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: "pnpm upload-manifest"

      # Update version for next version publish
      - script: node ./core/packages/internal-build-utils/cmd/cli.js bump-version-preview .
        displayName: Bump version to prerelease targets

      - template: /eng/pipelines/templates/pack.yml
        parameters:
          artifactName: npm-packages-next
          name: npm_packages_next

      # Publish Next playground
      - task: AzureCLI@1
        displayName: "Publish Azure playground"
        inputs:
          azureSubscription: "Azure SDK Engineering System"
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch \
              --auth-mode login \
              --destination $web \
              --account-name "cadlplayground" \
              --destination-path cadl-azure/ \
              --source "./packages/typespec-azure-playground-website/dist/" \
              --overwrite

    templateContext:
      # Optimize so each output doesn't create its own scan
      # https://eng.ms/docs/coreai/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/outputs#multiple-outputs
      outputParentDirectory: $(Build.ArtifactStagingDirectory)
      outputs:
        - output: pipelineArtifact
          path: $(Build.ArtifactStagingDirectory)/npm-packages-stable
          artifact: npm-packages-stable
          displayName: Publish npm stable packages(.tgz) as pipeline artifacts

        - output: pipelineArtifact
          path: $(Build.ArtifactStagingDirectory)/npm-packages-next
          artifact: npm-packages-next
          displayName: Publish npm next packages(.tgz) as pipeline artifacts
