jobs:
  - job: e2e
    displayName: "E2E Tests"

    pool:
      name: $(LINUXPOOL)
      image: $(LINUXVMIMAGE)
      os: linux

    variables:
      TYPESPEC_VS_CI_BUILD: true # Enable official Visual Studio extension build
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    steps:
      - checkout: self
        submodules: true

      - template: /eng/pipelines/templates/install.yml
      - template: /eng/pipelines/templates/install-browsers.yml

      - template: /eng/pipelines/templates/build.yml

      - script: node packages/e2e-tests/e2e-tests.mjs
        displayName: Azure Http Specs e2e tests

      - script: pnpm test:e2e
        displayName: E2E Tests
        # E2E test have issue in publish branch due to version being bumped but package not published yet.
        # E2E tests also fail in merge queue from publish branches due to the same reason.
        # Possible future alternative: parse merge queue branch for PR number, query GitHub and use that to determine if the branch is a publish branch.
        condition: and(succeeded(), and(
          eq(startsWith(variables['Build.SourceBranch'], 'refs/heads/gh-readonly-queue/'), false),
          eq(startsWith(variables['System.PullRequest.SourceBranch'], 'publish/'), false))
          )
