jobs:
  - job: e2e

    pool:
      name: $(LINUXPOOL)
      image: $(LINUXVMIMAGE)
      os: linux

    variables:
      TYPESPEC_VS_CI_BUILD: true # Enable official Visual Studio extension build
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    steps:
      - checkout: self
        submodules: true

      - template: /eng/pipelines/templates/install.yml
      - template: /eng/pipelines/templates/install-browsers.yml

      - template: /eng/pipelines/templates/build.yml

      - script: node packages/e2e-tests/e2e-tests.mjs
        displayName: Cadl Ranch e2e tests

      - script: pnpm e2e
        displayName: UI Tests
