import {
  BasicTestRunner,
  LinterRuleTester,
  createLinterRuleTester,
} from "@typespec/compiler/testing";
import { beforeEach, describe, it } from "vitest";
import { operationIdRule } from "../../src/rules/no-operation-id.js";
import { createAzureCoreTestRunner } from "../test-host.js";

describe("typespec-azure-core: avoid operation id rule", () => {
  let runner: BasicTestRunner;
  let tester: LinterRuleTester;

  beforeEach(async () => {
    runner = await createAzureCoreTestRunner();
    tester = createLinterRuleTester(runner, operationIdRule, "@azure-tools/typespec-azure-core");
  });

  describe("avoid use of @operationId in Azure specs", () => {
    it("emit warning if @operationId is used", async () => {
      await tester
        .expect(
          `
        using TypeSpec.OpenAPI;

        @operationId("foo")
        op test(): string;
      `
        )
        .toEmitDiagnostics({
          code: "@azure-tools/typespec-azure-core/no-operation-id",
          severity: "warning",
          message: `Operation ID is automatically generated by the OpenAPI emitters and should not normally be specified.`,
        });
    });
  });
});
