import { Tester } from "#test/test-host.js";
import { LinterRuleTester, createLinterRuleTester } from "@typespec/compiler/testing";
import { beforeEach, describe, it } from "vitest";
import { noOpenAPIRule } from "../../src/rules/no-openapi.js";

let tester: LinterRuleTester;

beforeEach(async () => {
  const runner = await Tester.import("@typespec/openapi").createInstance();
  tester = createLinterRuleTester(runner, noOpenAPIRule, "@azure-tools/typespec-azure-core");
});

describe("@operationId", () => {
  it("emit warning if @operationId is used", async () => {
    await tester
      .expect(
        `
        @OpenAPI.operationId("foo")
        op test(): string;
      `,
      )
      .toEmitDiagnostics({
        code: "@azure-tools/typespec-azure-core/no-openapi",
        message: `Operation ID is automatically generated by the OpenAPI emitters and should not normally be specified.`,
      });
  });
});

describe("@extension", () => {
  it("emit warning if @extension is used", async () => {
    await tester
      .expect(
        `
        @OpenAPI.extension("x-foo", "bar")
        op test(): string;
      `,
      )
      .toEmitDiagnostics({
        code: "@azure-tools/typespec-azure-core/no-openapi",
        message: `Azure specs should not be using decorator "$extension" from @typespec/openapi or @azure-tools/typespec-autorest. They will not apply to other emitter.`,
      });
  });
});

// Can't test as autorest is depending on azure.core

describe.skip("@example", () => {
  it("emit warning if @extension is used", async () => {
    await tester
      .expect(
        `
        @Autorest.example("x-foo", "bar")
        op test(): string;
      `,
      )
      .toEmitDiagnostics({
        code: "@azure-tools/typespec-azure-core/no-openapi",
      });
  });
});

// Can't test as autorest is depending on azure.core
describe.skip("@useRef", () => {
  it("emit warning if @useRef is used on model", async () => {
    await tester
      .expect(
        `
        @Autorest.useRef("foo.json")
        model Foo {}
      `,
      )
      .toEmitDiagnostics({
        code: "@azure-tools/typespec-azure-core/no-openapi",
      });
  });
});
