// Triage classifications from analysis of rule implementations.
// Maps rule IDs to tier classifications.

export const spectralTriage: Record<string, { tier: string; rationale: string }> = {
  // --- Infallible ---
  "arm-path-validation": { tier: "Infallible", rationale: "TypeSpec autorest emitter generates paths from @segment/@key decorators; ARM templates enforce valid resource path structure." },
  "AvoidAnonymousParameter": { tier: "Infallible", rationale: "TypeSpec always generates named models in definitions; inline anonymous schemas are never produced." },
  "AvoidAnonymousSchema": { tier: "Infallible", rationale: "TypeSpec always generates named models in definitions; inline anonymous schemas are never produced." },
  "ApiHost": { tier: "Infallible", rationale: "TypeSpec autorest emitter always generates valid host configuration." },
  "ApiVersionParameterRequired": {
    tier: "Unconstrained",
    rationale:
      "Custom ARM operations can omit ...ApiVersionParameter, and TypeSpec already surfaces direct api-version diagnostics for that authoring path.",
  },
  "HasApiVersionParameter": { tier: "Infallible", rationale: "TypeSpec autorest emitter always generates api-version parameter for all operations." },
  "HttpsSupportedScheme": { tier: "Infallible", rationale: "TypeSpec autorest emitter always generates https scheme for Azure specs." },
  "NamePropertyDefinitionInParameter": { tier: "Infallible", rationale: "TypeSpec autorest emitter always generates parameter 'name' property." },
  "ParameterNotDefinedInGlobalParameters": { tier: "Infallible", rationale: "TypeSpec emitter handles parameter placement correctly by design." },
  "PatchContentType": { tier: "Infallible", rationale: "TypeSpec autorest emitter generates correct content type for PATCH operations." },
  "SecurityDefinitionsStructure": { tier: "Template-enforced", rationale: "ARM resource-manager templates emit the canonical azure_auth OAuth2 security definition shape automatically." },
  "HostParametersValidation": { tier: "Infallible", rationale: "x-ms-parameterized-host structure is handled correctly by the emitter." },

  // --- Template-enforced ---
  "BodyParamRepeatedInfo": { tier: "Template-enforced", rationale: "ARM templates prevent body params from duplicating path/query parameters." },
  "Delete204Response": { tier: "Template-enforced", rationale: "ARM templates generate 204 for DELETE automatically; custom operations can override." },
  "DeleteInOperationName": { tier: "Template-enforced", rationale: "ARM templates generate 'Delete' verbs automatically; custom operations can use any operationId." },
  "DeleteResponseCodes": { tier: "Template-enforced", rationale: "ARM templates enforce correct DELETE response codes; custom operations can override." },
  "GetInOperationName": { tier: "Template-enforced", rationale: "ARM templates generate 'Get'/'List' verbs automatically; custom operations can override." },
  "GetResponseCodes": { tier: "Template-enforced", rationale: "ARM templates enforce 200 response for GET; custom operations could add other codes." },
  "ListInOperationName": { tier: "Template-enforced", rationale: "ARM templates enforce 'List' in operationId for pageable operations; custom ops can override." },
  "LroOriginalUri": { tier: "Template-enforced", rationale: "ARM templates for LROs require sibling GET operation; custom LROs can skip this." },
  "LroPatch202": { tier: "Template-enforced", rationale: "ARM PATCH LRO template enforces 202 response; custom PATCH operations could use other codes." },
  "LroWithOriginalUriAsFinalState": { tier: "Template-enforced", rationale: "ARM LRO templates set correct final-state-via; custom operations can override." },
  "LroPostMustNotUseOriginalUriAsFinalState": { tier: "Template-enforced", rationale: "ARM POST LRO templates set correct final-state-via; custom operations can override." },
  "LroStatusCodesReturnTypeSchema": { tier: "Template-enforced", rationale: "ARM LRO templates enforce schema on 200/201 responses; custom operations could use empty schemas." },
  "MissingDefaultResponse": { tier: "Template-enforced", rationale: "ARM templates include default error response; custom operations can omit it." },
  "MissingSegmentsInNestedResourceListOperation": { tier: "Template-enforced", rationale: "ARM templates enforce resource hierarchy in paths; custom operations can violate." },
  "OperationId": { tier: "Template-enforced", rationale: "ARM templates generate operationIds with required verb patterns; custom operations can use any format." },
  "PatchInOperationName": { tier: "Template-enforced", rationale: "ARM templates generate 'Update' verb for PATCH; custom operations can override." },
  "PatchResponseCodes": { tier: "Template-enforced", rationale: "ARM templates enforce specific PATCH response codes; custom operations can override." },
  "PostResponseCodes": { tier: "Template-enforced", rationale: "ARM templates enforce specific POST response codes; custom operations can override." },
  "ProvisioningStateMustBeReadOnly": { tier: "Template-enforced", rationale: "ARM templates set provisioningState as readOnly; custom models can allow mutation." },
  "ProvisioningStateValidation": { tier: "Template-enforced", rationale: "ARM templates enforce provisioning state enum values; custom enums can differ." },
  "ProvisioningStateSpecifiedForLROPatch": { tier: "Template-enforced", rationale: "ARM PATCH template enforces provisioningState in response; custom operations can omit." },
  "ProvisioningStateSpecifiedForLROPut": { tier: "Template-enforced", rationale: "ARM PUT template enforces provisioningState in 200/201 responses; custom operations can omit." },
  "PutInOperationName": { tier: "Template-enforced", rationale: "ARM templates generate 'Create' verb for PUT; custom operations can override." },
  "PutResponseCodes": { tier: "Template-enforced", rationale: "ARM templates enforce 200/201 for PUT; custom operations can use other codes." },
  "RequestBodyMustExistForPutPatch": { tier: "Template-enforced", rationale: "ARM templates require PUT/PATCH body; custom operations can omit body." },

  // --- Unconstrained ---
  "ArrayMustHaveType": { tier: "Infallible", rationale: "TypeSpec always generates type for array schemas." },
  "AvoidAdditionalProperties": { tier: "Unconstrained", rationale: "Users can use Record<T> which generates additionalProperties; templates don't prevent it." },
  "APIVersionPattern": { tier: "Unconstrained", rationale: "Version string format is user-controlled; TypeSpec doesn't enforce YYYY-MM-DD pattern." },
  "CollectionObjectPropertiesNaming": { tier: "Unconstrained", rationale: "User-defined models can have any property names; TypeSpec doesn't enforce 'value' property." },
  "ConsistentPatchProperties": { tier: "Unconstrained", rationale: "Users can define patch body properties independently; no enforcement of PUT schema consistency." },
  "ConsistentResponseBody": { tier: "Unconstrained", rationale: "Users can define different response schemas for PUT/GET/PATCH operations." },
  "ConsistentResponseSchemaForPut": { tier: "Unconstrained", rationale: "Users can define different schemas for PUT 200 vs 201 responses." },
  "DefaultInEnum": { tier: "Unconstrained", rationale: "Users can set enum defaults outside the enum list." },
  "DefinitionsPropertiesNamesCamelCase": { tier: "Unconstrained", rationale: "Property names come from TypeSpec model fields; users can define any naming convention." },
  "DeleteMustNotHaveRequestBody": { tier: "Template-enforced", rationale: "ARM templates don't add body to DELETE; custom operations could." },
  "DeleteResponseBodyEmpty": { tier: "Template-enforced", rationale: "ARM templates don't add body to DELETE 200/204 responses; custom operations could." },
  "DescriptiveDescriptionRequired": { tier: "Unconstrained", rationale: "Users can add empty @doc strings without TypeSpec validation." },
  "EnumInsteadOfBoolean": { tier: "Unconstrained", rationale: "Users can define boolean properties freely; TypeSpec doesn't enforce enum usage." },
  "ErrorResponse": { tier: "Unconstrained", rationale: "Error response schemas come from user-defined models; structure not enforced." },
  "EvenSegmentedPathForPutOperation": { tier: "Unconstrained", rationale: "Path segment count depends on @segment/@key decorators; templates don't enforce even segments." },
  "GetCollectionOnlyHasValueAndNextLink": { tier: "Unconstrained", rationale: "Collection GET response properties depend on user model definitions." },
  "GetMustNotHaveRequestBody": { tier: "Template-enforced", rationale: "ARM templates don't add body to GET; custom operations could." },
  "GetOperationMustNotBeLongRunning": { tier: "Template-enforced", rationale: "ARM templates don't add LRO to GET; custom operations could add x-ms-long-running-operation." },
  "GuidUsage": { tier: "Unconstrained", rationale: "Users can use format:'uuid' freely; TypeSpec doesn't restrict GUID usage." },
  "InvalidSkuModel": { tier: "Unconstrained", rationale: "Sku model properties depend on user model definition; TypeSpec doesn't enforce structure." },
  "LatestVersionOfCommonTypesMustBeUsed": { tier: "Unconstrained", rationale: "Users can reference any version of common-types." },
  "LocationMustHaveXmsMutability": { tier: "Template-enforced", rationale: "ARM TrackedResource templates emit location with x-ms-mutability ['read', 'create']; the previous raw repro was non-ARM and suppression-dependent." },
  "LroErrorContent": { tier: "Unconstrained", rationale: "LRO error response content structure depends on user model definitions." },
  "NoDuplicatePathsForScopeParameter": { tier: "Unconstrained", rationale: "Users can define duplicate paths with scope parameters." },
  "NoErrorCodeResponses": { tier: "Unconstrained", rationale: "Users can define custom error response codes." },
  "NonApplicationJsonType": { tier: "Unconstrained", rationale: "Users can specify non-JSON content types." },
  "OneUnderscoreInOperationId": { tier: "Unconstrained", rationale: "TypeSpec generates operationId from interface+method; users can customize." },
  "OperationIdNounConflictingModelNames": { tier: "Unconstrained", rationale: "operationId noun part can conflict with model names; TypeSpec doesn't validate." },
  "OperationIdNounVerb": { tier: "Unconstrained", rationale: "operationId can repeat noun in verb; TypeSpec doesn't enforce Noun_Verb pattern." },
  "OperationsApiSchema": { tier: "Unconstrained", rationale: "Operations API schema structure depends on user model definitions." },
  "OperationsApiTenantLevelOnly": { tier: "Unconstrained", rationale: "Users can define /operations paths at subscription scope." },
  "OperationsApiResponseSchema": { tier: "Unconstrained", rationale: "Operations API response schema structure depends on user model definitions." },
  "PaginationResponse": { tier: "Unconstrained", rationale: "Pageable response schema structure depends on user model definitions." },
  "ParameterLocation": { tier: "Unconstrained", rationale: "x-ms-parameter-location depends on user @extension decorator." },
  "ParameterNotUsingCommonTypes": { tier: "Unconstrained", rationale: "Users can redefine common-types parameters instead of using $ref." },
  "ParametersInPointGet": { tier: "Unconstrained", rationale: "Users can add query parameters to point GET operations." },
  "ParametersInPost": { tier: "Unconstrained", rationale: "Users can add query parameters to POST operations." },
  "ParametersSchemaAsTypeObject": { tier: "Unconstrained", rationale: "POST body parameter schema type depends on user model definitions." },
  "ParamNames": { tier: "Unconstrained", rationale: "Parameter naming depends on user definitions; no automatic convention enforcement." },
  "ParamNamesUnique": { tier: "Unconstrained", rationale: "Users can define duplicate parameter names (case-insensitive)." },
  "ParamOrder": { tier: "Infallible", rationale: "TypeSpec generates parameters in order matching path segments." },
  "PatchBodyParametersSchema": { tier: "Unconstrained", rationale: "PATCH body properties can have defaults, be required, or have x-ms-mutability:create." },
  "PatchIdentityProperty": { tier: "Unconstrained", rationale: "PATCH identity property handling depends on user model definitions." },
  "PatchPropertiesCorrespondToPutProperties": { tier: "Unconstrained", rationale: "PATCH body properties can differ from PUT; users can define non-overlapping sets." },
  "PatchSkuProperty": { tier: "Unconstrained", rationale: "PATCH SKU property handling depends on user model definitions." },
  "PathContainsResourceGroup": { tier: "Template-enforced", rationale: "ARM templates enforce subscription/RG in paths; custom operations can use any path." },
  "PathContainsResourceType": { tier: "Template-enforced", rationale: "ARM templates enforce provider/resource-type in paths; custom operations can use any path." },
  "PathContainsSubscriptionId": { tier: "Template-enforced", rationale: "ARM templates enforce subscription in paths; custom operations can use any path." },
  "PathForNestedResource": { tier: "Unconstrained", rationale: "Nested resource path structure depends on @segment/@key decorators." },
  "PathForResourceAction": { tier: "Unconstrained", rationale: "Resource action path structure depends on user operation definitions." },
  "PathForTrackedResourceTypes": { tier: "Unconstrained", rationale: "Path structure for tracked resources depends on user path definitions." },
  "PathParamNames": { tier: "Unconstrained", rationale: "Path parameter names can be inconsistent across paths." },
  "PathParamSchema": { tier: "Unconstrained", rationale: "Path parameter type, maxLength, pattern depend on user definitions." },
  "PathSegmentCasing": { tier: "Unconstrained", rationale: "Path segment casing depends on user @segment definitions." },
  "PropertiesTypeObjectNoDefinition": { tier: "Unconstrained", rationale: "Properties with type:object can be inline schemas." },
  "PutGetPatchSchema": { tier: "Unconstrained", rationale: "PUT/GET/PATCH operations can return different schemas." },
  "PutRequestResponseSchemeArm": { tier: "Unconstrained", rationale: "PUT request and response schemas can differ." },
  "QueryParametersInCollectionGet": { tier: "Unconstrained", rationale: "Users can add query parameters to collection GET operations." },
  "ReservedResourceNamesModelAsEnum": { tier: "Unconstrained", rationale: "Reserved resource names can be static path strings." },
  "ResourceNameRestriction": { tier: "Unconstrained", rationale: "Resource name parameters can lack pattern restrictions." },
  "ResponseSchemaSpecifiedForSuccessStatusCode": { tier: "Unconstrained", rationale: "PUT 200/201 responses can lack schemas." },
  "SchemaFormat": { tier: "Unconstrained", rationale: "Schema format field can use invalid values." },
  "SchemaTypeAndFormat": { tier: "Unconstrained", rationale: "Schema type/format combinations can be invalid." },
  "SkuValidation": { tier: "Unconstrained", rationale: "Sku model properties depend on user model definition." },
  "SubscriptionsAndResourceGroupCasing": {
    tier: "Template-enforced",
    rationale:
      "Standard ARM templates emit canonical casing, but custom Operations-interface routes can still misspell subscriptions/resourceGroups.",
  },
  "SummaryDescriptionMustNotBeSame": { tier: "Unconstrained", rationale: "Summary and description can be identical." },
  "SystemDataDefinitionsCommonTypes": {
    tier: "Prerequisite-blocked",
    rationale:
      "TrackedResource already emits common-types systemData; custom top-level replacements are rejected by arm-resource-invalid-envelope-property.",
  },
  "SystemDataInPropertiesBag": { tier: "Unconstrained", rationale: "Users can nest systemData in properties bag." },
  "TagsAreNotAllowedForProxyResources": { tier: "Unconstrained", rationale: "Tags can be in proxy resource properties; not enforced." },
  "TenantLevelAPIsNotAllowed": { tier: "Unconstrained", rationale: "Users can define tenant-level PUT operations." },
  "TrackedExtensionResourcesAreNotAllowed": { tier: "Unconstrained", rationale: "Extension resources can include location property." },
  "TrackedResourceTagsPropertyInRequest": { tier: "Unconstrained", rationale: "Tracked resource PUT body tags handling is user-controlled." },
  "UnSupportedPatchProperties": { tier: "Unconstrained", rationale: "PATCH body can include unsupported properties like id, name, type." },
  "ValidQueryParametersForPointOperations": { tier: "Unconstrained", rationale: "Point operations can have query parameters beyond api-version." },
  "VersionPolicy": { tier: "Unconstrained", rationale: "Version segments can appear in basePath/paths." },
  "WithXmsResource": { tier: "Unconstrained", rationale: "PUT operation schemas can lack x-ms-azure-resource extension." },
  "XmsClientNameParameter": { tier: "Unconstrained", rationale: "x-ms-client-name can equal the original parameter name." },
  "XmsClientNameProperty": { tier: "Unconstrained", rationale: "x-ms-client-name can equal the property name." },
  "XmsExamplesRequired": { tier: "Unconstrained", rationale: "Operations can lack x-ms-examples." },
  "XmsLongRunningOperationProperty": { tier: "Unconstrained", rationale: "Operations with LRO headers can lack x-ms-long-running-operation." },
  "XmsPageableForListCalls": {
    tier: "Template-enforced",
    rationale:
      "Standard ARM list templates emit x-ms-pageable; only raw custom GETs can omit it, and those already warn via arm-resource-operation.",
  },
  "XmsSecretInResponse": { tier: "Unconstrained", rationale: "Secret properties can lack x-ms-secret annotation." },

  // --- Dataplane-specific (az-dataplane.ts) ---
  "AdditionalPropertiesAndProperties": { tier: "Unconstrained", rationale: "Users can specify additionalProperties alongside properties." },
  "AdditionalPropertiesObject": { tier: "Unconstrained", rationale: "Users can define additionalProperties with type:object." },
  "ApiVersionEnum": { tier: "Unconstrained", rationale: "Users can define api-version as an enum." },
  "DefaultResponse": { tier: "Template-enforced", rationale: "ARM templates include default error response; custom operations can omit." },
  "Formdata": { tier: "Unconstrained", rationale: "Users can add formData parameters." },
  "HeaderDisallowed": { tier: "Unconstrained", rationale: "Users can define Authorization/Content-type/Accept header parameters." },
  "LroHeaders": { tier: "Unconstrained", rationale: "202 responses can lack Operation-Location header." },
  "MsPaths": { tier: "Unconstrained", rationale: "Users can use x-ms-paths." },
  "Nullable": { tier: "Unconstrained", rationale: "Users can add x-nullable." },
  "OperationSummaryOrDescription": { tier: "Unconstrained", rationale: "Operations can lack summary or description." },
  "ParameterDefault": { tier: "Unconstrained", rationale: "Required parameters can have defaults." },
  "ParameterDefaultNotAllowed": { tier: "Unconstrained", rationale: "Required parameters can have defaults." },
  "ParameterDescription": { tier: "Unconstrained", rationale: "Parameters can lack descriptions." },
  "ParameterDescriptionRequired": { tier: "Unconstrained", rationale: "Parameters can lack descriptions." },
  "PathCharacters": { tier: "Unconstrained", rationale: "Path can contain non-recommended characters." },
  "PathParameterNames": { tier: "Unconstrained", rationale: "Path parameter names can be inconsistent." },
  "PathParameterSchema": { tier: "Unconstrained", rationale: "Path parameters can lack maxLength/pattern." },
  "Post201Response": { tier: "Unconstrained", rationale: "POST operations can return 201." },
  "PropertyDescription": { tier: "Unconstrained", rationale: "Properties can lack descriptions." },
  "PropertyType": { tier: "Unconstrained", rationale: "Properties can lack type." },
  "PutPath": { tier: "Unconstrained", rationale: "PUT paths can lack final path parameter." },
  "PutRequestResponseScheme": { tier: "Unconstrained", rationale: "PUT request and response schemas can differ." },
  "RequestBodyNotAllowed": { tier: "Unconstrained", rationale: "Data-plane GET and DELETE operations can explicitly declare body parameters." },
  "RequestBodyOptional": { tier: "Unconstrained", rationale: "Request body can be optional." },
  "SchemaDescriptionOrTitle": { tier: "Unconstrained", rationale: "Schemas can lack description or title." },
  "SchemaNamesConvention": { tier: "Unconstrained", rationale: "Schema names depend on TypeSpec model names; PascalCase not enforced." },
  "SecurityDefinitionDescription": { tier: "Unconstrained", rationale: "Security definitions can lack descriptions." },
  "SuccessResponseBody": { tier: "Unconstrained", rationale: "Success responses can lack body schemas." },
  "VersionConvention": { tier: "Unconstrained", rationale: "Version format is user-controlled." },
  "LongRunningResponseStatusCodeDataPlane": { tier: "Unconstrained", rationale: "LRO options extension depends on user configuration." },

  // --- Additional rules (naming variants in ruleset files) ---
  "AvoidAnonymousTypes": { tier: "Infallible", rationale: "TypeSpec always generates named definitions; anonymous inline types not produced." },
  "AvoidMsdnReferences": { tier: "Unconstrained", rationale: "Users can reference MSDN URLs in descriptions." },
  "AvoidNestedProperties": { tier: "Unconstrained", rationale: "Users can nest properties deeply; TypeSpec doesn't restrict depth." },
  "InvalidVerbUsed": { tier: "Infallible", rationale: "TypeSpec HTTP decorators only generate valid HTTP methods." },
  "LongRunningOperationsOptionsValidator": { tier: "Template-enforced", rationale: "ARM LRO templates set valid x-ms-long-running-operation-options; custom ops can set invalid values." },
  "LroExtension": {
    tier: "Prerequisite-blocked",
    rationale:
      "The ARM violating repro needs arm-post-operation-response-codes suppression, and explicit x-ms-long-running-operation authoring is blocked by no-openapi unless suppressed.",
  },
  "LroLocationHeader": { tier: "Template-enforced", rationale: "ARM LRO templates include Location header; custom LROs can omit it." },
  "MutabilityWithReadOnly": {
    tier: "Prerequisite-blocked",
    rationale:
      "The violating shape depends on @OpenAPI.extension(\"x-ms-mutability\", ...), which is already blocked by @azure-tools/typespec-azure-core/no-openapi unless suppressed.",
  },
  "NextLinkPropertyMustExist": { tier: "Unconstrained", rationale: "Users can reference nonexistent nextLink properties in x-ms-pageable." },
  "NonEmptyClientName": { tier: "Infallible", rationale: "TypeSpec generates non-empty x-ms-client-name values." },
  "OperationIdSingleUnderscore": { tier: "Infallible", rationale: "TypeSpec generates operationId as Interface_Method with single underscore." },
  "OperationsApiSchemaUsesCommonTypes": { tier: "Unconstrained", rationale: "Operations API schema source depends on user imports and definitions." },
  "PageableRequires200Response": { tier: "Unconstrained", rationale: "Pageable operations can lack 200 response." },
  "ParameterNamesConvention": { tier: "Unconstrained", rationale: "Parameter naming depends on user definitions." },
  "ParameterNamesUnique": { tier: "Unconstrained", rationale: "Users can define duplicate parameter names." },
  "ParameterOrder": { tier: "Infallible", rationale: "TypeSpec generates parameters in order matching path segments." },
  "PutGetPatchResponseSchema": { tier: "Unconstrained", rationale: "PUT/GET/PATCH can return different schemas." },
  "RepeatedPathInfo": { tier: "Unconstrained", rationale: "Body parameters can repeat path/query info." },
  "RequestSchemaForTrackedResourcesMustHaveTags": { tier: "Template-enforced", rationale: "ARM TrackedResource base model includes tags; custom models could omit." },
  "ResourceHasXMsResourceEnabled": { tier: "Template-enforced", rationale: "ARM base models set x-ms-azure-resource; custom resource definitions could omit." },
  "SubscriptionIdParameterInOperations": { tier: "Infallible", rationale: "ARM library always generates subscriptionId parameter for subscription-scoped operations." },
  "SummaryAndDescriptionMustNotBeSame": { tier: "Unconstrained", rationale: "Summary and description can be identical." },
  "ValidFormats": { tier: "Unconstrained", rationale: "Schema format values are user-controlled." },
  "XMSLongRunningOperationProperty": {
    tier: "Unconstrained",
    rationale:
      "Custom ARM POST actions can emit Location or Azure-AsyncOperation headers without long-running metadata; the local native lint now covers those authorable gaps.",
  },
  "XMSSecretInResponse": { tier: "Unconstrained", rationale: "Secret properties can lack x-ms-secret annotation." },
  "XmsClientName": { tier: "Unconstrained", rationale: "x-ms-client-name usage is user-controlled." },
  "XmsParameterLocation": { tier: "Unconstrained", rationale: "x-ms-parameter-location depends on user @extension." },
  "XmsPathsMustOverloadPaths": { tier: "Unconstrained", rationale: "x-ms-paths can contain paths not overloading existing paths." },
  "XmsResourceInPutResponse": {
    tier: "Prerequisite-blocked",
    rationale:
      "The raw violating PUT needs arm-resource-operation suppression, compliant authoring needs no-openapi suppression for x-ms-azure-resource, and current template PUT hits are emitter-structure dependent rather than a clean native-lint target.",
  },
  "docLinkLocale": { tier: "Unconstrained", rationale: "Documentation links can contain locale segments like /en-us/." },
};

export const nativeTriage: Record<string, { tier: string; rationale: string }> = {
  // Native ARM rules
  "AllTrackedResourcesMustHaveDelete": { tier: "Unconstrained", rationale: "User controls whether to add delete operations to tracked resources." },
  "AllProxyResourcesShouldHaveDelete": { tier: "Unconstrained", rationale: "User controls whether to add delete operations to proxy resources." },
  "RequiredPropertiesMissingInResourceModel": { tier: "Template-enforced", rationale: "ARM library base models (TrackedResource/ProxyResource) provide name, id, type as readonly." },
  "ArmResourcePropertiesBag": { tier: "Unconstrained", rationale: "Users control what properties they add; templates don't prevent duplicating ARM top-level properties." },
  "TrackedResourcePatchOperation": { tier: "Unconstrained", rationale: "User controls which operations exist on resources; templates don't enforce patch." },
  "BodyTopLevelProperties": { tier: "Unconstrained", rationale: "Users can add arbitrary top-level properties to resource models." },
  "TrackedResourceBeyondsThirdLevel": { tier: "Unconstrained", rationale: "Path depth is determined by @segment/@key decorators; templates don't limit nesting." },
  "TrackedResourcesMustHavePut": { tier: "Unconstrained", rationale: "User controls which operations exist; not all resources have put in their interface." },
  "PathResourceProviderMatchNamespace": { tier: "Template-enforced", rationale: "@armProviderNamespace and @segment enforce path structure matching namespace." },
  "OperationsAPIImplementation": { tier: "Unconstrained", rationale: "Operations endpoint requires explicit user definition." },
  "XmsPageableListByRGAndSubscriptions": { tier: "Unconstrained", rationale: "x-ms-pageable consistency between list operations is user-controlled." },
  "ImplementPrivateEndpointAPIs": { tier: "Unconstrained", rationale: "Private endpoint paths are user-controlled custom operations." },

  // Legacy rules
  "AllResourcesMustHaveGetOperation": { tier: "Unconstrained", rationale: "User controls whether to add get operations." },
  "ArraySchemaMustHaveItems": { tier: "Infallible", rationale: "TypeSpec array models always generate items schema automatically." },
  "AvoidEmptyResponseSchema": { tier: "Infallible", rationale: "TypeSpec always generates non-empty response schemas." },
  "AzureResourceTagsSchema": { tier: "Template-enforced", rationale: "ARM templates provide tags with correct schema; violation requires overriding base model." },
  "ControlCharactersAreNotAllowed": { tier: "Infallible", rationale: "TypeSpec source code can't contain control characters; emitter never produces them." },
  "DefaultErrorResponseSchema": { tier: "Infallible", rationale: "TypeSpec autorest emitter generates proper error response schemas." },
  "DeleteOperationResponses": { tier: "Template-enforced", rationale: "ARM templates enforce delete responses; custom operations can violate." },
  "DeprecatedXmsCodeGenerationSetting": { tier: "Unconstrained", rationale: "x-ms-code-generation-settings can be added via @extension." },
  "DescriptionMustNotBeNodeName": { tier: "Unconstrained", rationale: "Users write descriptions; TypeSpec doesn't enforce they differ from node names." },
  "EnumMustHaveType": { tier: "Infallible", rationale: "TypeSpec enums always have explicit type." },
  "EnumMustNotHaveEmptyValue": { tier: "Infallible", rationale: "TypeSpec enum members can't have empty values." },
  "EnumMustRespectType": { tier: "Infallible", rationale: "TypeSpec enforces enum values match declared type at compile time." },
  "EnumUniqueValue": { tier: "Infallible", rationale: "TypeSpec enforces unique enum values at compile time." },
  "ExtensionResourcePathPattern": { tier: "Unconstrained", rationale: "Path structure for extension resources is user-controlled." },
  "GetCollectionResponseSchema": { tier: "Unconstrained", rationale: "User controls collection response structure." },
  "IntegerTypeMustHaveFormat": { tier: "Infallible", rationale: "TypeSpec always generates format for integer types." },
  "LicenseHeaderMustNotBeSpecified": { tier: "Unconstrained", rationale: "x-ms-code-generation-settings.header can be added via @extension." },
  "MissingTypeObject": { tier: "Infallible", rationale: "TypeSpec always generates type:object for models with properties." },
  "MissingXmsErrorResponse": { tier: "Unconstrained", rationale: "x-ms-error-response is user-controlled via @extension." },
  "NestedResourcesMustHaveListOperation": { tier: "Unconstrained", rationale: "User controls which operations exist on nested resources." },
  "OperationIdRequired": { tier: "Infallible", rationale: "TypeSpec autorest emitter always generates operationId." },
  "PageableOperation": { tier: "Unconstrained", rationale: "x-ms-pageable is user-controlled; templates don't enforce it for array responses." },
  "ParametersOrder": { tier: "Infallible", rationale: "TypeSpec generates parameters in order matching path segments." },
  "PathResourceProviderNamePascalCase": { tier: "Template-enforced", rationale: "@armProviderNamespace enforces PascalCase provider names." },
  "PathResourceTypeNameCamelCase": { tier: "Unconstrained", rationale: "@segment values are user-defined; casing not enforced." },
  "PostOperationIdContainsUrlVerb": { tier: "Unconstrained", rationale: "User controls operationId naming." },
  "PreviewVersionOverOneYear": { tier: "Unconstrained", rationale: "Version string is user-controlled; TypeSpec doesn't enforce timing." },
  "PrivateEndpointResourceSchemaValidation": { tier: "Unconstrained", rationale: "Private endpoint resource schemas are user-defined." },
  "RequiredDefaultResponse": { tier: "Template-enforced", rationale: "ARM templates include default error response; custom operations can omit." },
  "RequiredReadOnlySystemData": { tier: "Template-enforced", rationale: "ARM templates provide readonly systemData; violation requires overriding." },
  "Rpaas_ResourceProvisioningState": { tier: "Unconstrained", rationale: "provisioningState is user-controlled." },
  "TopLevelResourcesListByResourceGroup": { tier: "Unconstrained", rationale: "User controls which list operations exist." },
  "TopLevelResourcesListBySubscription": { tier: "Unconstrained", rationale: "User controls which list operations exist." },
  "UniqueClientParameterName": { tier: "Infallible", rationale: "TypeSpec generates unique parameter names." },
  "UniqueModelName": { tier: "Infallible", rationale: "TypeSpec model names are unique by design." },
  "UniqueXmsEnumName": { tier: "Unconstrained", rationale: "x-ms-enum names are user-controlled." },
  "UniqueXmsExample": { tier: "Unconstrained", rationale: "x-ms-examples are user-defined." },
  "ValidResponseCodeRequired": { tier: "Infallible", rationale: "TypeSpec always generates valid response codes." },
  "XmsEnumValidation": { tier: "Unconstrained", rationale: "x-ms-enum is user-controlled via @extension." },
  "XmsIdentifierValidation": { tier: "Unconstrained", rationale: "x-ms-identifiers is user-controlled." },
  "XmsPageableMustHaveCorrespondingResponse": { tier: "Unconstrained", rationale: "x-ms-pageable properties are user-controlled." },
};
