name: Benchmark Comment

on:
  workflow_run:
    workflows: ["Benchmark"]
    types:
      - completed

permissions:
  actions: read
  pull-requests: write

jobs:
  comment:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/benchmark-comment-run.yml
    with:
      run-id: ${{ github.event.workflow_run.id }}
      header: benchmark-results
      comment-file: benchmark-comment.md
    permissions:
      actions: read
      pull-requests: write
    secrets: inherit
