name: "typespec-java / CI"

on:
  pull_request:
    branches:
      - main
      - release/*
    paths:
      - "packages/typespec-java/**"
      - ".github/workflows/ci-java.yml"
  merge_group:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - name: Install dependencies
        run: pnpm install
      - name: Build typespec-java package
        run: pnpm turbo run --filter "@azure-tools/typespec-java..." build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - name: Install dependencies
        run: pnpm install
      - name: Run linters
        working-directory: packages/typespec-java
        run: pnpm lint
