name: Auto-label linter rule changes

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "packages/typespec-azure-core/src/rules/**/*.ts"
      - "packages/typespec-azure-core/src/rules/**/*.js"
      - "packages/typespec-azure-resource-manager/src/rules/**/*.ts"
      - "packages/typespec-azure-resource-manager/src/rules/**/*.js"
      - "packages/typespec-client-generator-core/src/rules/**/*.ts"
      - "packages/typespec-client-generator-core/src/rules/**/*.js"

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["int:azure-specs"],
            });
