name: Test Fix github release
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - fix/github-release

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - run: npx @chronus/github create-releases --repo azure/typespec-azure --publish-summary ./report-summary-temp.json
        name: Create github releases
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
