emit:
  - "@azure-tools/typespec-autorest"
  - "@azure-tools/typespec-python"
  - "@azure-tools/typespec-ts"
  - "@typespec/http-client-js"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    output-file: "{emitter-output-dir}/{service-name}/{version}/openapi.json"
  "@azure-tools/typespec-python":
    namespace: "azure.mgmt.contosobenchmark"
  "@azure-tools/typespec-ts":
    flavor: azure
    azure-arm: true
    package-details:
      name: "@azure/arm-contosobenchmark"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
